export const hrLmsUiCopy = {
  accessDenied: {
    title: "Learning access restricted",
    description: "You do not have permission to view this learning surface.",
  },
  courses: {
    surfaceHeaderTitle: "Course catalog",
    searchLabel: "Search courses",
    searchPlaceholder: "Title, code, category, provider",
    emptyTitle: "No courses yet",
    emptyDescription: "Publish a course to populate the LMS catalog.",
    colCode: "Code",
    colTitle: "Title",
    colCategory: "Category",
    colType: "Type",
    colStatus: "Status",
  },
  employeeOverview: {
    surfaceHeaderTitle: "My learning",
    emptyTitle: "No learning assigned",
    emptyDescription: "Enrolled courses and progress appear here.",
    colCourse: "Course",
    colStatus: "Status",
    colProgress: "Progress",
  },
  managerOverview: {
    surfaceHeaderTitle: "Team learning",
    emptyTitle: "No team learning data",
    emptyDescription: "Team assignments and completion appear here.",
    colEmployee: "Employee",
    colMandatory: "Mandatory incomplete",
    colProgress: "Completion",
  },
  adminOverview: {
    surfaceHeaderTitle: "Organization learning",
    emptyTitle: "No organization learning data",
    emptyDescription: "Org-wide completion and overdue training appear here.",
    colDepartment: "Department",
    colCompletion: "Completion",
    colOverdue: "Overdue",
    colCompliance: "Compliance risk",
  },
  reports: {
    surfaceHeaderTitle: "Learning reports",
    emptyTitle: "No report rows",
    emptyDescription: "Adjust filters or assign learning to generate reports.",
    colGroup: "Group",
    colRows: "Rows",
    colCompletion: "Completion %",
    colOverdue: "Overdue",
  },
  audit: {
    surfaceHeaderTitle: "LMS audit trail",
    emptyTitle: "No audit events",
    emptyDescription: "Course setup, assignments, and completions are audited here.",
    colAction: "Action",
    colSummary: "Summary",
    colWhen: "When",
  },
} as const;
