export const hrTalentCareerPathingUiCopy = {
  page: {
    title: "Career pathing & development plans",
    description:
      "Frameworks, target roles, skill gaps, development plans, mentoring, and readiness for your organization.",
  },
  accessDenied: {
    title: "Career pathing access required",
    description:
      "You need HR talent read permission to view career pathing and development plans.",
  },
  overview: {
    sectionTitle: "Development overview",
    frameworks: "Career frameworks",
    targetRoles: "Target roles",
    activePlans: "Active plans",
    overdueMilestones: "Overdue milestones",
    nearReady: "Near-ready employees",
  },
  frameworks: {
    sectionTitle: "Career path frameworks",
    surfaceHeaderTitle: "Career path frameworks",
    searchLabel: "Search frameworks",
    searchPlaceholder: "Code or name",
    emptyTitle: "No frameworks yet",
    emptyDescription: "Create a career path framework to define progression tracks.",
    colCode: "Code",
    colName: "Name",
    colPathKind: "Path kind",
    colStatus: "Status",
    pickerLabel: "Selected framework",
  },
  frameworkStages: {
    sectionTitle: "Framework stages",
    surfaceHeaderTitle: "Stages for selected framework",
    emptyTitle: "No stages defined",
    emptyDescription: "Add ordered stages to the selected career path framework.",
    colOrder: "Order",
    colCode: "Code",
    colName: "Stage",
    colDuration: "Expected months",
  },
  targetRoles: {
    sectionTitle: "Target roles & aspirations",
    surfaceHeaderTitle: "Target roles",
    emptyTitle: "No target roles",
    emptyDescription: "Employees and managers can define preferred target roles.",
    colEmployee: "Employee",
    colTargetRole: "Target role",
    colJobFamily: "Job family",
    colGrade: "Grade",
    colSource: "Source",
    pickerLabel: "Employee for skill gaps",
  },
  skillGaps: {
    sectionTitle: "Role and skill gap compare",
    surfaceHeaderTitle: "Role and skill gap compare",
    searchLabel: "Filter gaps",
    searchPlaceholder: "Skill or competency",
    emptyTitle: "No gaps to compare",
    emptyDescription: "Select an employee with a target role to compare requirements.",
    colDimension: "Dimension",
    colRequired: "Required",
    colCurrent: "Current",
    colGap: "Gap",
  },
  plans: {
    sectionTitle: "Development plans",
    surfaceHeaderTitle: "Development plans",
    searchLabel: "Search plans",
    searchPlaceholder: "Code or title",
    emptyTitle: "No development plans",
    emptyDescription: "Create personalized development plans linked to target roles.",
    colEmployee: "Employee",
    colCode: "Code",
    colTitle: "Title",
    colStatus: "Status",
    colTargetDate: "Target date",
    pickerLabel: "Selected plan",
  },
  planGoals: {
    sectionTitle: "Plan goals",
    surfaceHeaderTitle: "Development goals",
    emptyTitle: "No goals on this plan",
    emptyDescription: "Add skill, competency, certification, or leadership goals.",
    colTitle: "Goal",
    colType: "Type",
    colStatus: "Status",
    colPriority: "Priority",
    colProgress: "Progress",
    colActions: "Actions",
    trailingUpdateLabel: "Update status",
  },
  learningActions: {
    sectionTitle: "Learning actions",
    surfaceHeaderTitle: "Learning actions",
    emptyTitle: "No learning actions",
    emptyDescription: "Link training courses or external learning to this plan.",
    colTitle: "Action",
    colStatus: "Status",
    colDueDate: "Due",
    colTraining: "Training ref",
  },
  stretchAssignments: {
    sectionTitle: "Stretch assignments",
    surfaceHeaderTitle: "Stretch assignments",
    emptyTitle: "No stretch assignments",
    emptyDescription: "Assign projects or acting roles for leadership exposure.",
    colTitle: "Assignment",
    colKind: "Kind",
    colStatus: "Status",
    colDates: "Dates",
  },
  discussions: {
    sectionTitle: "Career discussions",
    surfaceHeaderTitle: "Career discussions",
    emptyTitle: "No career discussions",
    emptyDescription: "Record career conversations and agreed actions.",
    colEmployee: "Employee",
    colDate: "Discussion date",
    colNextReview: "Next review",
    colNotes: "Notes",
  },
  readiness: {
    sectionTitle: "Readiness snapshots",
    surfaceHeaderTitle: "Role readiness",
    searchLabel: "Search readiness",
    searchPlaceholder: "Employee or level",
    emptyTitle: "No readiness snapshots",
    emptyDescription: "Compute readiness after target roles and development plans exist.",
    colEmployee: "Employee",
    colTargetRole: "Target role",
    colLevel: "Readiness",
    colScore: "Score",
    colComputedAt: "Computed",
    exportCsvLabel: "Export readiness CSV",
  },
  forms: {
    aspirationTitle: "Career aspiration",
    frameworkTitle: "Framework",
    frameworkStatusTitle: "Framework status",
    stageTitle: "Framework stage",
    planTitle: "Create development plan",
    managerReviewTitle: "Manager development review",
    sessionLogTitle: "Mentor or coach session",
  },
  reports: {
    sectionTitle: "Career development reports",
    surfaceHeaderTitle: "Development reports",
    searchLabel: "Search reports",
    searchPlaceholder: "Group or dimension",
    emptyTitle: "No report rows",
    emptyDescription: "Run a development summary report to populate this view.",
    colGroup: "Group",
    colEmployees: "Employees",
    colPlans: "Plans",
    colNearReady: "Near ready",
    colOverdue: "Overdue milestones",
    colCompletedGoals: "Completed goals",
  },
  auditTrail: {
    sectionTitle: "Career pathing audit trail",
    surfaceHeaderTitle: "Audit trail",
    searchLabel: "Search audit",
    searchPlaceholder: "Action or employee",
    emptyTitle: "No audit events",
    emptyDescription: "Career pathing mutations will appear here.",
    colOccurredAt: "Occurred",
    colAction: "Action",
    colEmployee: "Employee",
    colSummary: "Summary",
    colActor: "Actor",
    colMetadata: "Metadata",
  },
} as const;

/** @deprecated Use `hrTalentCareerPathingUiCopy`. */
export const hrCareerPathUiCopy = hrTalentCareerPathingUiCopy;
export const hrCareerPathingUiCopy = hrTalentCareerPathingUiCopy;

export const hrCareerPathFrameworksColumnsId =
  "hr.talent.career-pathing.frameworks.columns";
export const hrCareerPathTargetRolesColumnsId =
  "hr.talent.career-pathing.target-roles.columns";
export const hrCareerPathSkillGapsColumnsId =
  "hr.talent.career-pathing.skill-gaps.columns";
export const hrCareerPathPlansColumnsId = "hr.talent.career-pathing.plans.columns";
export const hrCareerPathPlanGoalsColumnsId =
  "hr.talent.career-pathing.plan-goals.columns";
