export type {
  ApprovalReadinessVerdict,
  SystemAdminApprovalMode,
  SystemAdminApprovalRule,
  SystemAdminApprovalRuleDetail,
  SystemAdminApprovalRuleEditorDefaults,
  SystemAdminApprovalRuleListRow,
  SystemAdminApprovalRuleStatus,
  SystemAdminApprovalActivityRow,
  SystemAdminApproverRoleOption,
} from "./system-admin.approval-rule.contract";
export {
  APPROVAL_RULE_DEFAULT_MODULE_KEY,
  APPROVAL_RULE_DEFAULT_TARGET_TYPE,
  APPROVAL_RULE_DELEGATION_VALID_DAYS_MAX,
  APPROVAL_RULE_DELEGATION_VALID_DAYS_MIN,
  APPROVAL_RULE_ESCALATION_HOURS_MAX,
  APPROVAL_RULE_ESCALATION_HOURS_MIN,
  APPROVAL_RULE_FIELD_MAX_LENGTH,
  APPROVAL_RULE_KEY_MAX_LENGTH,
  APPROVAL_RULE_LIST_SEARCH_FIELDS,
  APPROVAL_RULE_MIN_APPROVALS_MAX,
  APPROVAL_RULE_MIN_APPROVALS_MIN,
  APPROVAL_RULE_MIN_ESCALATION_HOURS_FROM_MINUTES,
  APPROVAL_RULE_NAME_MAX_LENGTH,
  APPROVAL_RULE_ROLE_KEYS_INPUT_MAX_LENGTH,
} from "./system-admin.approval-rule.limits.shared";
