export const hrCsfUiCopy = {
  accessDenied: {
    title: "Competency & skills access denied",
    description:
      "You do not have permission to view competency, skill, or readiness data for this organization.",
  },
  page: {
    title: "Competency & skills",
    description:
      "Define competencies and skills, assess proficiency, analyze gaps, and expose readiness to talent programs.",
  },
  nav: {
    hub: "Overview",
    reports: "Reports",
    audit: "Audit trail",
    matching: "Skill matching",
  },
  competencies: {
    surfaceHeaderTitle: "Competency library",
    searchLabel: "Search competencies",
    searchPlaceholder: "Search by code or name",
    emptyTitle: "No competencies",
    emptyDescription: "Create competencies to map role expectations.",
    colCode: "Code",
    colName: "Name",
    colCategory: "Category",
    colStatus: "Status",
  },
  skills: {
    surfaceHeaderTitle: "Skill library",
    searchLabel: "Search skills",
    searchPlaceholder: "Search by code or name",
    emptyTitle: "No skills",
    emptyDescription: "Create skills to track workforce capability.",
    colCode: "Code",
    colName: "Name",
    colCategory: "Category",
    colStatus: "Status",
  },
  gaps: {
    surfaceHeaderTitle: "Skill & competency gaps",
    searchLabel: "Search gaps",
    searchPlaceholder: "Search by employee or item",
    emptyTitle: "No gaps identified",
    emptyDescription: "Gaps appear when required proficiency exceeds current level.",
    colEmployee: "Employee",
    colItem: "Item",
    colKind: "Kind",
    colRequired: "Required",
    colCurrent: "Current",
    colSeverity: "Severity",
    colPriority: "Priority",
  },
  reports: {
    pageTitle: "Competency & skill reports",
    pageDescription:
      "Workforce capability slices by employee, role, department, job family, grade, and proficiency.",
    surfaceHeaderTitle: "Capability reports",
    searchLabel: "Search report groups",
    searchPlaceholder: "Filter grouped rows",
    emptyTitle: "No report rows",
    emptyDescription: "Adjust filters or seed employee proficiency data.",
    colGroup: "Group",
    colEmployees: "Employees",
    colSkills: "Skills",
    colCompetencies: "Competencies",
    colGaps: "Gaps",
    colAvgProficiency: "Avg proficiency",
  },
  audit: {
    pageTitle: "Competency & skills audit trail",
    pageDescription:
      "Every setup, mapping, assessment, gap analysis, recommendation, and profile update is recorded.",
    surfaceHeaderTitle: "Audit events",
    searchLabel: "Search audit",
    searchPlaceholder: "Search by action or summary",
    emptyTitle: "No audit events",
    emptyDescription: "Audit events appear as CSF actions occur.",
    colAction: "Action",
    colSummary: "Summary",
    colActor: "Actor",
    colWhen: "When",
  },
  matching: {
    pageTitle: "Skill matching",
    pageDescription:
      "Identify employees who match required skills for a role, project, or critical position.",
    surfaceHeaderTitle: "Matching results",
    searchLabel: "Search matches",
    searchPlaceholder: "Search by employee or department",
    emptyTitle: "No matches",
    emptyDescription: "Set a target code to run a skill match query.",
    colEmployee: "Employee",
    colDepartment: "Department",
    colScore: "Match score",
    colMatched: "Matched skills",
    colMissingCritical: "Missing critical",
  },
  integration: {
    trainingExposure: "Training & Development gaps",
    lmsRecommendations: "LMS recommendations",
    performanceRefs: "Performance appraisal refs",
    successionReadiness: "Succession readiness",
  },
} as const;
