export const hrLifecycleUiCopy = {
  page: {
    title: "Employee lifecycle",
    description:
      "Track employment stages, onboarding and offboarding cases, notice period, probation, and movement events.",
  },
  accessDenied: {
    title: "Access restricted",
    description: "You do not have permission to view employee lifecycle.",
  },
  overview: {
    statsTitle: "Lifecycle posture",
    statsDescription: "Headcount and transition follow-up for the active roster.",
    rosterTitle: "Employee roster",
    rosterDescription:
      "Current employment stage, probation dates, and pending scheduled transitions.",
    searchLabel: "Search employees",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colStage: "Stage",
    colProbationEnd: "Probation end",
    colConfirmation: "Confirmed",
    colPending: "Pending transitions",
    colNextEffective: "Next effective",
    emptyTitle: "No employees match",
    emptyDescription: "Adjust search or employment stage filters.",
    surfaceHeaderTitle: "Lifecycle roster",
    trailingScheduleLabel: "Schedule change",
    trailingToStatus: "Target stage",
    trailingEffectiveDate: "Effective date",
    trailingReason: "Reason",
    trailingApprovalRef: "Approval reference",
  },
  pendingTransitions: {
    sectionTitle: "Scheduled transitions",
    sectionDescription:
      "Future-dated employment status changes awaiting effective date.",
    searchLabel: "Search scheduled transitions",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colFrom: "From",
    colTo: "To",
    colEffective: "Effective",
    colDue: "Due posture",
    colReason: "Reason",
    emptyTitle: "No scheduled transitions",
    emptyDescription: "Schedule a status change from the employee roster.",
    surfaceHeaderTitle: "Pending transitions",
    trailingCancelLabel: "Cancel schedule",
  },
  probationDue: {
    sectionTitle: "Probation review",
    sectionDescription:
      "Employees on probation with an end date within the next 30 days or already overdue.",
    searchLabel: "Search probation reviews",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colProbationEnd: "Probation end",
    colReviewPosture: "Review posture",
    colStage: "Stage",
    emptyTitle: "No probation reviews due",
    emptyDescription: "No employees require probation review in the current window.",
    surfaceHeaderTitle: "Probation due",
    trailingOutcomeLabel: "Record outcome",
    trailingOutcome: "Outcome",
    trailingProbationEnd: "New probation end",
    trailingEffectiveDate: "Effective date",
    trailingReason: "Reason",
    trailingApprovalRef: "Approval reference",
  },
  onboardingCases: {
    sectionTitle: "Onboarding checklists",
    sectionDescription:
      "In-progress onboarding cases with default checklist items (HRM-LCY-004–006).",
    searchLabel: "Search onboarding cases",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colCaseStatus: "Case status",
    colTargetStatus: "Target stage",
    colStarted: "Started",
    emptyTitle: "No active onboarding cases",
    emptyDescription:
      "Start a checklist when an employee is in the onboarding stage.",
    surfaceHeaderTitle: "Onboarding cases",
  },
  noticePeriod: {
    sectionTitle: "Notice period",
    sectionDescription:
      "Employees in notice period with last working date when offboarding has started.",
    searchLabel: "Search notice period",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colLastWorking: "Last working",
    colOffboardingCase: "Offboarding",
    emptyTitle: "No employees in notice period",
    emptyDescription: "Initiate notice period from the exit pathways panel.",
    surfaceHeaderTitle: "Notice period",
    trailingStartOffboarding: "Start offboarding",
  },
  offboardingCases: {
    sectionTitle: "Offboarding clearance",
    sectionDescription:
      "Active offboarding cases with default clearance checklist (HRM-LCY-018–020).",
    searchLabel: "Search offboarding cases",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colCaseStatus: "Case status",
    colLastWorking: "Last working",
    colPriorStage: "Prior stage",
    emptyTitle: "No active offboarding cases",
    emptyDescription: "Start offboarding from notice period or the exit panel.",
    surfaceHeaderTitle: "Offboarding cases",
  },
  exit: {
    panelTitle: "Exit pathways",
    panelDescription:
      "Initiate notice period, start offboarding, or open an onboarding checklist.",
    employeeLabel: "Employee",
    reasonLabel: "Reason",
    approvalRefLabel: "Approval reference",
    effectiveDateLabel: "Effective date",
    lastWorkingLabel: "Last working date",
    noticeSubmitLabel: "Initiate notice period",
    offboardingSubmitLabel: "Start offboarding",
    onboardingSubmitLabel: "Start onboarding checklist",
    targetStatusLabel: "Target stage after onboarding",
  },
  movement: {
    panelTitle: "Record movement",
    panelDescription:
      "Promotion, transfer, demotion, or placement change without changing employment stage.",
    employeeLabel: "Employee",
    movementKindLabel: "Movement type",
    departmentLabel: "Department ID",
    positionLabel: "Position ID",
    managerLabel: "Manager employee ID",
    effectiveDateLabel: "Effective date",
    reasonLabel: "Reason",
    approvalRefLabel: "Approval reference",
    submitLabel: "Record movement",
  },
  auditTrail: {
    sectionTitle: "Lifecycle audit trail",
    sectionDescription:
      "Append-only history of lifecycle events for the organization.",
    searchLabel: "Search audit trail",
    searchPlaceholder: "Employee, event kind, or reason",
    colEffective: "Effective",
    colEmployee: "Employee",
    colKind: "Event",
    colFrom: "From",
    colTo: "To",
    colReason: "Reason",
    emptyTitle: "No lifecycle events",
    emptyDescription: "Lifecycle events appear when stages or movements are recorded.",
    surfaceHeaderTitle: "Audit trail",
  },
} as const;
