export {
  HR_EXPENSE_APPROVE_CAPABILITY,
  HR_EXPENSE_EXCEPTION_APPROVE_CAPABILITY,
  HR_EXPENSE_FINANCE_APPROVE_CAPABILITY,
  HR_EXPENSE_READ_CAPABILITY,
  HR_EXPENSE_WRITE_CAPABILITY,
} from "./hr.payroll.exp-constants.shared";
