import type { SystemAdminUserRow } from "../contracts";

export const systemAdminUsersGalleryRows: readonly SystemAdminUserRow[] = [
  {
    id: "member-gallery-1",
    membershipId: "member-gallery-1",
    invitationId: null,
    authUserId: "user-gallery-1",
    name: "Alex Admin",
    email: "alex@example.com",
    status: "active",
    membership: "active",
    roles: ["admin"],
    lastActive: "27 May 2026",
    invitedAt: null,
    joinedAt: new Date("2026-01-15T00:00:00.000Z"),
    createdAt: new Date("2026-01-15T00:00:00.000Z"),
  },
  {
    id: "invite-gallery-1",
    membershipId: null,
    invitationId: "invite-gallery-1",
    authUserId: null,
    name: "Pending invite",
    email: "pending@example.com",
    status: "invited",
    membership: "pending",
    roles: ["staff"],
    lastActive: "Not joined",
    invitedAt: new Date("2026-05-20T00:00:00.000Z"),
    joinedAt: null,
    createdAt: new Date("2026-05-20T00:00:00.000Z"),
  },
  {
    id: "member-gallery-2",
    membershipId: "member-gallery-2",
    invitationId: null,
    authUserId: "user-gallery-2",
    name: "Sam Staff",
    email: "sam@example.com",
    status: "suspended",
    membership: "suspended",
    roles: ["staff"],
    lastActive: "12 May 2026",
    invitedAt: null,
    joinedAt: new Date("2026-02-01T00:00:00.000Z"),
    createdAt: new Date("2026-02-01T00:00:00.000Z"),
  },
  {
    id: "member-gallery-3",
    membershipId: "member-gallery-3",
    invitationId: null,
    authUserId: "user-gallery-3",
    name: "Riley Removed",
    email: "riley@example.com",
    status: "removed",
    membership: "removed",
    roles: ["staff"],
    lastActive: "Removed",
    invitedAt: null,
    joinedAt: null,
    createdAt: new Date("2026-03-01T00:00:00.000Z"),
  },
] as const;
