export const hrFwaUiCopy = {
  page: {
    title: "Flexible Work Arrangements",
    description:
      "Manage hybrid, remote, compressed, and flexible schedules with approvals, compliance monitoring, and lifecycle reviews.",
  },
  accessDenied: {
    title: "Flexible work access required",
    description:
      "You need flexible work read permission to view arrangements, requests, and compliance data.",
  },
  arrangements: {
    sectionTitle: "Active arrangements",
    surfaceHeaderTitle: "Flexible work arrangements",
    searchLabel: "Search arrangements",
    searchPlaceholder: "Employee name or number",
    emptyTitle: "No arrangements yet",
    emptyDescription:
      "Approved flexible work arrangements appear here with review and renewal dates.",
    colEmployee: "Employee",
    colKind: "Type",
    colStatus: "Status",
    colEffective: "Effective",
    colReview: "Review",
    colRenewal: "Renewal",
  },
  requests: {
    sectionTitle: "Requests",
    surfaceHeaderTitle: "Flexible work requests",
    searchLabel: "Search requests",
    searchPlaceholder: "Employee or reason",
    emptyTitle: "No requests",
    emptyDescription: "Submitted flexible work requests awaiting or after decision.",
    colEmployee: "Employee",
    colKind: "Type",
    colStatus: "Status",
    colSubmitted: "Submitted",
  },
  compliance: {
    sectionTitle: "Compliance breaches",
    surfaceHeaderTitle: "Policy compliance",
    searchLabel: "Search breaches",
    searchPlaceholder: "Employee or breach kind",
    emptyTitle: "No open breaches",
    emptyDescription: "Policy breaches such as excessive remote days are listed here.",
    colKind: "Breach",
    colStatus: "Status",
    colDetected: "Detected",
  },
  reports: {
    sectionTitle: "Reports",
    surfaceHeaderTitle: "Flexible work summary",
    emptyTitle: "No report data",
    emptyDescription: "Adjust period or grouping to generate a flexible work report.",
    colGroup: "Group",
    colActive: "Active",
    colPending: "Pending requests",
    colBreaches: "Open breaches",
  },
  audit: {
    sectionTitle: "Audit trail",
    surfaceHeaderTitle: "FWA audit events",
    searchLabel: "Search audit",
    searchPlaceholder: "Action or summary",
    emptyTitle: "No audit events",
    emptyDescription: "Request, approval, renewal, and compliance actions are recorded here.",
    colAction: "Action",
    colSummary: "Summary",
    colWhen: "When",
  },
} as const;
