export const hrTimeClockUiCopy = {
  page: {
    title: "Time Clock Integration",
    description:
      "Connect physical and digital time clocks, map employees, capture raw punches, monitor sync health, and expose validated attendance to Leave & Attendance, Overtime, and Payroll.",
  },
  accessDenied: {
    title: "Time clock access restricted",
    description:
      "You do not have permission to view time clock integration for this organization.",
  },
  overview: {
    sectionTitle: "Sync health overview",
    deviceCount: "Registered devices",
    activeDevices: "Active devices",
    openExceptions: "Open punch exceptions",
    failedSyncs: "Failed sync batches",
    validPunches24h: "Valid punches (24h)",
    pendingValidation: "Pending validation",
  },
  devices: {
    sectionTitle: "Time clock devices",
    surfaceHeaderTitle: "Device registry",
    searchLabel: "Search devices",
    searchPlaceholder: "Device ID, name, or location",
    emptyTitle: "No devices registered",
    emptyDescription:
      "Register biometric terminals, card readers, kiosks, web clocks, or mobile clocks to begin punch capture.",
    colDevice: "Device",
    colType: "Type",
    colLocation: "Location",
    colStatus: "Status",
    colLastSync: "Last sync",
    colActions: "Actions",
  },
  mappings: {
    sectionTitle: "Employee device mappings",
    surfaceHeaderTitle: "Employee mappings",
    searchLabel: "Search mappings",
    searchPlaceholder: "Employee, badge, or device user ID",
    emptyTitle: "No employee mappings",
    emptyDescription:
      "Map badge IDs, biometric IDs, or device user IDs to employee records before punch validation.",
    colEmployee: "Employee",
    colDevice: "Device",
    colDeviceUserId: "Device user ID",
    colBadgeId: "Badge ID",
    colStatus: "Status",
    colActions: "Actions",
  },
  rawPunches: {
    sectionTitle: "Raw punch records",
    surfaceHeaderTitle: "Raw punches",
    searchLabel: "Search punches",
    searchPlaceholder: "Employee, device, or punch type",
    emptyTitle: "No punch records",
    emptyDescription:
      "Raw punches are preserved separately from approved attendance outcomes (HRM-TCI-029).",
    colEmployee: "Employee",
    colDevice: "Device",
    colPunchType: "Punch type",
    colPunchedAt: "Punched at",
    colValidation: "Validation",
    colSource: "Source",
  },
  exceptions: {
    sectionTitle: "Punch exceptions",
    surfaceHeaderTitle: "Exception flags",
    searchLabel: "Search exceptions",
    searchPlaceholder: "Employee, device, or exception code",
    emptyTitle: "No punch exceptions",
    emptyDescription:
      "Missing, duplicate, early, late, and unmatched punches appear here for correction workflow.",
    colEmployee: "Employee",
    colException: "Exception",
    colDevice: "Device",
    colPunchType: "Punch type",
    colPunchedAt: "Punched at",
    colValidation: "Validation",
    colActions: "Actions",
  },
  syncBatches: {
    sectionTitle: "Device sync batches",
    surfaceHeaderTitle: "Sync batches",
    searchLabel: "Search sync batches",
    searchPlaceholder: "Device, batch key, or location",
    emptyTitle: "No sync batches",
    emptyDescription:
      "Automated and scheduled sync runs are tracked with idempotency and failure diagnostics.",
    colDevice: "Device",
    colBatchKey: "Batch key",
    colStatus: "Status",
    colStarted: "Started",
    colRecords: "Records",
    colError: "Error",
  },
  lamExport: {
    sectionTitle: "LAM exposure",
    surfaceHeaderTitle: "Validated punches for LAM",
    searchLabel: "Search validated punches",
    searchPlaceholder: "Employee or device",
    emptyTitle: "No validated punches",
    emptyDescription:
      "Validated punch records exposed to Leave & Attendance Management (HRM-TCI-021).",
    colEmployee: "Employee",
    colDevice: "Device",
    colLocation: "Location",
    colPunchType: "Punch type",
    colPunchedAt: "Punched at",
    colWorkDate: "Work date",
  },
  overtimeRefs: {
    sectionTitle: "Overtime references",
    surfaceHeaderTitle: "Work-hour references",
    searchLabel: "Search work hours",
    searchPlaceholder: "Employee or work date",
    emptyTitle: "No work-hour references",
    emptyDescription:
      "Actual work-hour records for Overtime Management validation (HRM-TCI-022).",
    colEmployee: "Employee",
    colWorkDate: "Work date",
    colHours: "Hours",
    colPunchSpan: "Punch span",
    colStatus: "Status",
  },
  payrollRefs: {
    sectionTitle: "Payroll readiness",
    surfaceHeaderTitle: "Approved attendance via LAM",
    searchLabel: "Search payroll refs",
    searchPlaceholder: "Employee or work date",
    emptyTitle: "No payroll-ready attendance",
    emptyDescription:
      "Approved attendance outcomes routed to Payroll through LAM (HRM-TCI-023).",
    colEmployee: "Employee",
    colWorkDate: "Work date",
    colAttendanceStatus: "Attendance status",
    colPayrollRef: "Payroll reference",
    colSource: "Source",
  },
  reports: {
    sectionTitle: "Time clock reports",
    surfaceHeaderTitle: "Reports",
    searchLabel: "Group reports by",
    searchPlaceholder: "employee, device, location, exception, sync status",
    emptyTitle: "No report rows",
    emptyDescription:
      "Summaries by employee, device, location, department, date, exception type, and sync status.",
    panelDescription:
      "Export CSV reports for punches, exceptions, sync status, and device activity. Each export includes up to 5,000 rows.",
    pendingLabel: "Exporting…",
    colGroup: "Group",
    colLabel: "Label",
    colCount: "Count",
    colHours: "Hours",
    exportLabels: {
      punches: "Export punches CSV",
      exceptions: "Export exceptions CSV",
      sync: "Export sync status CSV",
      devices: "Export devices CSV",
    },
  },
  auditTrail: {
    sectionTitle: "Audit trail",
    surfaceHeaderTitle: "Audit events",
    searchLabel: "Search audit trail",
    searchPlaceholder: "Action, device, employee, or summary",
    emptyTitle: "No audit events",
    emptyDescription:
      "Device setup, mapping, punch capture, sync, validation, correction, and exception actions.",
    colOccurred: "Occurred",
    colAction: "Action",
    colSummary: "Summary",
    colDevice: "Device",
    colEmployee: "Employee",
  },
  forms: {
    registerDeviceTitle: "Register device",
    registerMappingTitle: "Create mapping",
  },
} as const;
