export const hrOrgUiCopy = {
  page: {
    title: "Organization",
    description:
      "Maintain org units, positions, reporting lines, headcount, and hierarchy visualization.",
  },
  accessDenied: {
    title: "Organization access restricted",
    description:
      "You need HR organization read permission to view the org chart workbench.",
  },
  overview: {
    structureLabel: "Structure posture",
    headcountLabel: "Headcount and vacancies",
  },
  orgChart: {
    title: "Organization chart",
    description: "Parent-child hierarchy of active organization units.",
    emptyTitle: "No organization units",
    emptyDescription: "Create organization units to visualize the hierarchy.",
  },
  units: {
    surfaceHeaderTitle: "Organization units",
    searchLabel: "Search units",
    searchPlaceholder: "Code or name",
    emptyTitle: "No organization units",
    emptyDescription: "Create legal entities, departments, teams, or locations.",
    colCode: "Code",
    colName: "Name",
    colType: "Type",
    colParent: "Parent",
    colManager: "Manager",
    colStatus: "Status",
    colLocation: "Location",
    colEffectiveFrom: "Effective from",
  },
  positions: {
    surfaceHeaderTitle: "Positions",
    searchLabel: "Search positions",
    searchPlaceholder: "Code, title, or department",
    emptyTitle: "No positions",
    emptyDescription: "Create positions within organization units.",
    colCode: "Code",
    colTitle: "Title",
    colDepartment: "Department",
    colOccupancy: "Occupancy",
    colManager: "Manager",
    colLocation: "Location",
    colStatus: "Status",
  },
  reportingLines: {
    surfaceHeaderTitle: "Reporting lines",
    searchLabel: "Search reporting",
    searchPlaceholder: "Employee or manager",
    emptyTitle: "No reporting lines",
    emptyDescription:
      "Maintain direct, dotted-line, and matrix reporting relationships.",
    colEmployee: "Employee",
    colManager: "Manager",
    colType: "Type",
    colDepartment: "Department",
    colPosition: "Position",
    colEffectiveFrom: "Effective from",
  },
  vacancies: {
    surfaceHeaderTitle: "Vacant positions",
    searchLabel: "Search vacancies",
    searchPlaceholder: "Code, title, or department",
    emptyTitle: "No vacant positions",
    emptyDescription: "All active positions are currently filled.",
  },
  headcount: {
    surfaceHeaderTitle: "Headcount by unit",
    searchLabel: "Search units",
    searchPlaceholder: "Code or name",
    emptyTitle: "No headcount data",
    emptyDescription: "Headcount appears when organization units exist.",
    colUnit: "Unit",
    colType: "Type",
    colFilled: "Filled",
    colVacant: "Vacant",
    colTotal: "Positions",
  },
  auditTrail: {
    surfaceHeaderTitle: "Structure audit trail",
    searchLabel: "Search audit",
    searchPlaceholder: "Entity id or payload",
    emptyTitle: "No audit events",
    emptyDescription: "Organization changes will appear here.",
    colEntity: "Entity",
    colAction: "Action",
    colEffectiveFrom: "Effective from",
    colChangedAt: "Changed at",
  },
  forms: {
    orgUnitTitle: "Create or update organization unit",
    positionTitle: "Create or update position",
    reportingLineTitle: "Create or update reporting line",
    submitLabel: "Save",
  },
} as const;
