export const SYSTEM_ADMIN_DATA_MANAGEMENT_QUERY_LIMIT = 100;

export const SYSTEM_ADMIN_IMPORT_SOURCE_LABEL_MAX_LENGTH = 120;

export const SYSTEM_ADMIN_IMPORT_FILENAME_MAX_LENGTH = 180;

export const SYSTEM_ADMIN_IMPORT_SOURCE_DATA_MAX_BYTES = 256_000;

export const SYSTEM_ADMIN_DATA_MANAGEMENT_AUDIT_TARGET_TYPE =
  "system_admin_data_management" as const;
