export const hrRecordsUiCopy = {
  page: {
    title: "Employee records",
    description:
      "Official employee master profiles, placement references, profile completeness, and assignment history.",
    addEmployeeLabel: "Add employee",
  },
  accessDenied: {
    title: "Access restricted",
    description: "You do not have permission to view employee records.",
  },
  sensitiveAccess: {
    title: "Sensitive employee information restricted",
    description:
      "Email, identity, phone, date of birth, and address values are masked. Request hr.employees.sensitive.read for full visibility and inline updates.",
    directoryDescription:
      "Directory email and inline profile updates require hr.employees.sensitive.read.",
    detailDescription:
      "Profile identity, contact, and address fields are masked on this page.",
  },
  overview: {
    statsTitle: "Workforce posture",
    statsDescription:
      "Active roster, incomplete profiles, and assignment history coverage.",
  },
  directory: {
    sectionTitle: "Employee directory",
    sectionDescription:
      "Master employee roster with current placement and employment status.",
    searchLabel: "Search employees",
    searchPlaceholder: "Employee number, name, or email",
    colEmployee: "Employee",
    colStatus: "Status",
    colEmail: "Email",
    colDepartment: "Department",
    colPosition: "Position",
    colManager: "Manager",
    colStartDate: "Start date",
    emptyTitle: "No employees match",
    emptyDescription: "Adjust search or employment status filters.",
    surfaceHeaderTitle: "Employee directory",
  },
  incomplete: {
    sectionTitle: "Incomplete profiles",
    sectionDescription:
      "Active employees missing mandatory identity, contact, or placement data.",
    searchLabel: "Search incomplete profiles",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colStatus: "Status",
    colMissing: "Missing fields",
    emptyTitle: "All profiles complete",
    emptyDescription: "No active employees are missing mandatory master data.",
    surfaceHeaderTitle: "Incomplete profiles",
  },
  assignments: {
    sectionTitle: "Assignment history",
    sectionDescription:
      "Effective-dated department, position, and manager assignment changes.",
    searchLabel: "Search assignment history",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colDepartment: "Department",
    colPosition: "Position",
    colManager: "Manager",
    colEffectiveFrom: "Effective from",
    colEffectiveTo: "Effective to",
    colStatus: "Status",
    colReason: "Reason",
    emptyTitle: "No assignment history",
    emptyDescription: "Placement changes will appear here when recorded.",
    surfaceHeaderTitle: "Assignment history",
  },
  create: {
    accessDeniedTitle: "Access restricted",
    accessDeniedDescription: "You don't have permission to add employees.",
    backLabel: "Back to employees",
    panelTitle: "Add employee",
    panelDescription:
      "Create a new employee master record with identity and contact details.",
    employeeNumberLabel: "Employee number",
    legalNameLabel: "Legal name",
    preferredNameLabel: "Preferred name",
    emailLabel: "Work email",
    employmentStartDateLabel: "Employment start date",
    employmentTypeLabel: "Employment type",
    identityNumberLabel: "Identity number",
    phoneNumberLabel: "Phone number",
    personalEmailLabel: "Personal email",
    submitLabel: "Create employee",
  },
  auditTrail: {
    sectionTitle: "Record audit trail",
    sectionDescription:
      "Field-level changes, assignments, and profile updates across employee master records.",
    searchLabel: "Search audit trail",
    searchPlaceholder: "Employee, event kind, or reason",
    colEffective: "Effective",
    colEmployee: "Employee",
    colKind: "Event",
    colField: "Field",
    colChange: "Change",
    colReason: "Reason",
    emptyTitle: "No audit events",
    emptyDescription: "Employee record changes will appear here when recorded.",
    surfaceHeaderTitle: "Record audit trail",
  },
  statusHistory: {
    sectionTitle: "Status history",
    sectionDescription:
      "Lifecycle and record employment status transitions with effective dates.",
    searchLabel: "Search status history",
    searchPlaceholder: "Employee, status, or reason",
    colEffective: "Effective",
    colEmployee: "Employee",
    colSource: "Source",
    colKind: "Event",
    colFrom: "From",
    colTo: "To",
    colReason: "Reason",
    emptyTitle: "No status history",
    emptyDescription: "Employment status changes will appear here when applied.",
    surfaceHeaderTitle: "Status history",
  },
  documentReferences: {
    sectionTitle: "Document references",
    sectionDescription:
      "Active employee document links maintained by document management.",
    searchLabel: "Search document references",
    searchPlaceholder: "Employee, title, or document type",
    colTitle: "Document",
    colEmployee: "Employee",
    colType: "Type",
    colVerification: "Verification",
    colEffectiveFrom: "Effective from",
    colEffectiveTo: "Effective to",
    emptyTitle: "No linked documents",
    emptyDescription: "Registered employee documents will appear here.",
    surfaceHeaderTitle: "Document references",
  },
  separated: {
    sectionTitle: "Separated employees",
    sectionDescription:
      "Archived and separated employee records preserved for historical reference.",
    searchLabel: "Search separated roster",
    searchPlaceholder: "Employee number or name",
    colEmployee: "Employee",
    colStatus: "Status",
    colDepartment: "Department",
    colPosition: "Position",
    colArchived: "Archived",
    colStartDate: "Start date",
    emptyTitle: "No separated employees",
    emptyDescription: "Separated or archived employees will appear here.",
    surfaceHeaderTitle: "Separated employees",
    trailingRehireLabel: "Rehire",
  },
  trailing: {
    actionsHeader: "Actions",
    updateLabel: "Update",
    assignmentLabel: "Assign",
    archiveLabel: "Archive",
    rehireLabel: "Rehire",
    reasonLabel: "Reason",
    effectiveDateLabel: "Effective date",
    employeeNumberLabel: "Employee number",
    legalNameLabel: "Legal name",
    preferredNameLabel: "Preferred name",
    emailLabel: "Work email",
    departmentIdLabel: "Department ID",
    positionIdLabel: "Position ID",
    managerIdLabel: "Manager employee ID",
  },
  detail: {
    backLabel: "Back to employee records",
    profileTitle: "Employee profile",
    profileDescription:
      "Official master profile with current placement and employment status.",
    notFoundTitle: "Employee not found",
    notFoundDescription:
      "This employee record does not exist or is outside your organization.",
    employeeNumberLabel: "Employee number",
    legalNameLabel: "Legal name",
    preferredNameLabel: "Preferred name",
    emailLabel: "Work email",
    statusLabel: "Employment status",
    departmentLabel: "Department",
    positionLabel: "Position",
    managerLabel: "Manager",
    identityLabel: "Identity number",
    phoneLabel: "Phone",
    dateOfBirthLabel: "Date of birth",
    addressLabel: "Residential address",
    archivedLabel: "Archived",
    updatedLabel: "Last updated",
  },
} as const;
