export const SYSTEM_ADMIN_AUDIT_DEFAULT_PAGE_SIZE = 25;

export const SYSTEM_ADMIN_AUDIT_EXPORT_ROW_LIMIT = 5_000;

export const SYSTEM_ADMIN_AUDIT_COVERAGE_GAPS_PREVIEW_LIMIT = 8;

export const SYSTEM_ADMIN_AUDIT_METADATA_REDACT_MAX_DEPTH = 6;

export const SYSTEM_ADMIN_AUDIT_METADATA_REDACT_MAX_STRING_LENGTH = 500;

export const SYSTEM_ADMIN_AUDIT_TARGET_TIMELINE_DEFAULT_LIMIT = 50;

export const SYSTEM_ADMIN_AUDIT_RETENTION_LIST_LIMIT = 50;

export const SYSTEM_ADMIN_AUDIT_COVERAGE_MODULE_LIMIT = 200;

export const SYSTEM_ADMIN_AUDIT_COVERAGE_CAPABILITY_LIMIT = 500;
