import { createModuleFeatureMetadata } from "@afenda/kernel/feature-metadata";

/**
 * Governed metadata door.
 * Runtime authority stays in server actions, queries, and policies.
 */
export const {
  moduleId,
  buildRecordListSurface,
  buildWorkItemListSurface,
  buildCountStatGrid,
  buildStatGrid,
  buildOverviewStatGrid,
  buildSavedViewsListSurface,
  buildDocumentRegistryListSurface,
  buildRecordDetailTabs,
  buildWorkItemDetailTabs,
  buildWorkItemKanbanSurface,
  getListSurfaceKeys,
  getOverviewStatSurfaceKey,
  getStatSurfaceKey,
  getWorkItemKanbanSurfaceKey,
} = createModuleFeatureMetadata("hr");

type HrUiCopyPage = {
  title: string;
  description: string;
  addEmployeeLabel?: string;
};

export const hrAttendanceUiCopy = {
  page: {
    title: "Attendance",
    description: "Attendance is managed by HR Suite.",
  } satisfies HrUiCopyPage,
};

export { hrLamUiCopy as hrLeaveUiCopy } from "./time-attendance/leave-attendance-management/metadata";

export {
  getHrComplianceListSurfaceKeys,
  HR_COMPLIANCE_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_COMPLIANCE_LIST_SEARCH_PARAMS_BY_KEY,
  HR_COMPLIANCE_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_COMPLIANCE_LIST_SURFACE_KEYS,
  HR_COMPLIANCE_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrComplianceExceptionsSurfaceKey,
  hrComplianceFilingsSurfaceKey,
  hrComplianceLaborLawRequirementsSurfaceKey,
  hrComplianceStatutoryRequirementsSurfaceKey,
  hrComplianceObligationsSurfaceKey,
  hrCompliancePolicyAcknowledgementsSurfaceKey,
  hrComplianceRegulatoryCalendarSurfaceKey,
  hrComplianceAlertsSurfaceKey,
  hrComplianceSafetyTrainingRequirementsSurfaceKey,
  hrComplianceWorkAuthDocumentsSurfaceKey,
  hrComplianceWorkEligibilitySurfaceKey,
  hrComplianceWorkplaceSafetyRequirementsSurfaceKey,
  hrComplianceUiCopy,
  parseHrComplianceSearchParams,
  toHrCompliancePageModelInput,
  type HrComplianceSearchParams,
  type HrComplianceListSurfaceKey,
  hrComplianceExceptionSearchParam,
  hrComplianceFilingSearchParam,
  hrComplianceRegulatoryCalendarSearchParam,
  hrComplianceAlertsSearchParam,
  hrComplianceLaborLawSearchParam,
  hrComplianceStatutorySearchParam,
  hrComplianceObligationSearchParam,
  hrCompliancePolicyAcknowledgementSearchParam,
  hrComplianceSafetyTrainingSearchParam,
  hrComplianceWorkplaceSafetySearchParam,
  hrComplianceWorkAuthDocumentSearchParam,
  hrComplianceWorkEligibilitySearchParam,
  hrComplianceEvidenceLinksSurfaceKey,
  hrComplianceEvidenceLinksSearchParam,
  hrComplianceAuditTrailSurfaceKey,
  hrComplianceAuditTrailSearchParam,
  hrComplianceReviewQueueSurfaceKey,
  hrComplianceReviewQueueSearchParam,
} from "./employee-management/compliance-regulatory-tracking/metadata";

export {
  hrComplianceRoutePaths,
  type HrComplianceRoutePath,
} from "./employee-management/compliance-regulatory-tracking/contracts/hr.workforce.compliance-route.contract";

export {
  buildHrSuiteListSearchToolbar,
  buildHrSuiteOperationalListSurface,
  buildHrSuiteSearchParamModelFields,
  buildHrSuiteSearchParamsBySurfaceKey,
  defineHrSuiteActionDescriptor,
  defineHrSuiteSearchParamRegistry,
  resolveHrModuleNavItems,
  resolveHrSuiteListTrailingAction,
  type BuildHrSuiteOperationalListSurfaceInput,
  type HrModuleNavItem,
  type HrSuiteListColumn,
  type HrSuiteListRow,
  type HrSuiteListSearchToolbarInput,
  type HrSuiteListSurfaceProfile,
  type HrSuiteSearchParamRegistryEntry,
} from "./hr-suite-integration/metadata";

export {
  getHrDocumentsListSurfaceKeys,
  HR_DOCUMENTS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_DOCUMENTS_LIST_SEARCH_PARAMS_BY_KEY,
  HR_DOCUMENTS_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_DOCUMENTS_LIST_SURFACE_KEYS,
  HR_DOCUMENTS_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrDocumentsRepositorySurfaceKey,
  hrDocumentsRequirementsSurfaceKey,
  hrDocumentsMissingSurfaceKey,
  hrDocumentsExpiringSurfaceKey,
  hrDocumentsRetentionSurfaceKey,
  hrDocumentsAuditTrailSurfaceKey,
  hrDocumentsAcknowledgmentsSurfaceKey,
  hrDocumentsUiCopy,
  parseHrDocumentsSearchParams,
  toHrDocumentsPageModelInput,
  type HrDocumentsSearchParams,
  type HrDocumentsListSurfaceKey,
  hrDocumentsRepositorySearchParam,
  hrDocumentsRequirementsSearchParam,
  hrDocumentsMissingSearchParam,
  hrDocumentsExpiringSearchParam,
  hrDocumentsRetentionSearchParam,
  hrDocumentsAuditTrailSearchParam,
  hrDocumentsAcknowledgmentsSearchParam,
} from "./employee-management/documents-management/metadata";

export {
  hrDocumentsRoutePaths,
  type HrDocumentsRoutePath,
} from "./employee-management/documents-management/contracts/hr.workforce.documents-route.contract";

export {
  getHrOrgListSurfaceKeys,
  HR_ORG_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_ORG_LIST_SEARCH_PARAMS_BY_KEY,
  HR_ORG_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_ORG_LIST_SURFACE_KEYS,
  HR_ORG_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrOrgUnitsSurfaceKey,
  hrOrgPositionsSurfaceKey,
  hrOrgReportingLinesSurfaceKey,
  hrOrgVacanciesSurfaceKey,
  hrOrgHeadcountSurfaceKey,
  hrOrgAuditTrailSurfaceKey,
  hrOrgUiCopy,
  parseHrOrgSearchParams,
  toHrOrgPageModelInput,
  type HrOrgSearchParams,
  type HrOrgListSurfaceKey,
  hrOrgUnitsSearchParam,
  hrOrgPositionsSearchParam,
  hrOrgReportingLinesSearchParam,
  hrOrgVacanciesSearchParam,
  hrOrgHeadcountSearchParam,
  hrOrgAuditTrailSearchParam,
  hrOrgUnitTypeFilterParam,
  hrOrgStatusFilterParam,
  hrOrgLocationFilterParam,
  hrOrgLegalEntityFilterParam,
} from "./employee-management/organizational-chart-hierarchy/metadata";

export {
  hrOrgRoutePaths,
  type HrOrgRoutePath,
} from "./employee-management/organizational-chart-hierarchy/contracts/hr.workforce.org-route.contract";

export {
  getHrRecordsListSurfaceKeys,
  HR_RECORDS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_RECORDS_LIST_SEARCH_PARAMS_BY_KEY,
  HR_RECORDS_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_RECORDS_LIST_SURFACE_KEYS,
  HR_RECORDS_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrRecordsDirectorySurfaceKey,
  hrRecordsIncompleteSurfaceKey,
  hrRecordsAssignmentsSurfaceKey,
  hrRecordsAuditTrailSurfaceKey,
  hrRecordsStatusHistorySurfaceKey,
  hrRecordsDocumentReferencesSurfaceKey,
  hrRecordsSeparatedSurfaceKey,
  hrRecordsUiCopy,
  parseHrRecordsSearchParams,
  toHrRecordsPageModelInput,
  type HrRecordsSearchParams,
  type HrRecordsListSurfaceKey,
  hrRecordsDirectorySearchParam,
  hrRecordsIncompleteSearchParam,
  hrRecordsAssignmentsSearchParam,
  hrRecordsAuditTrailSearchParam,
  hrRecordsStatusHistorySearchParam,
  hrRecordsDocumentReferencesSearchParam,
  hrRecordsSeparatedSearchParam,
  hrRecordsEmploymentStatusFilterParam,
} from "./employee-management/employee-records-management/metadata";

export {
  hrRecordsRoutePaths,
  hrEmployeeDetailRoutePath,
  type HrRecordsRoutePath,
} from "./employee-management/employee-records-management/contracts/hr.workforce.records-route.contract";

/** @deprecated Use hrRecordsUiCopy */
export { hrRecordsUiCopy as hrEmployeesUiCopy } from "./employee-management/employee-records-management/metadata";

export {
  getHrFwaListSurfaceKeys,
  HR_FWA_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_FWA_LIST_SEARCH_PARAMS_BY_KEY,
  HR_FWA_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_FWA_LIST_SURFACE_KEYS,
  hrFwaArrangementsSurfaceKey,
  hrFwaArrangementsSearchParam,
  hrFwaRequestsSurfaceKey,
  hrFwaRequestsSearchParam,
  hrFwaComplianceSurfaceKey,
  hrFwaComplianceSearchParam,
  hrFwaReportsSurfaceKey,
  hrFwaAuditTrailSurfaceKey,
  hrFwaAuditTrailSearchParam,
  hrFwaUiCopy,
  parseHrFwaSearchParams,
  toHrFwaPageModelInput,
  type HrFwaSearchParams,
  type HrFwaListSurfaceKey,
  hrFwaRoutePaths,
  type HrFwaRoutePath,
  assertFwaCoverageComplete,
  FWA_REQUIREMENT_COVERAGE,
} from "./time-attendance/flexible-work-arrangement-tracking/metadata";

export {
  getHrGeoListSurfaceKeys,
  HR_GEO_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_GEO_LIST_SEARCH_PARAMS_BY_KEY,
  HR_GEO_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_GEO_LIST_SURFACE_KEYS,
  hrGeoGeofencesSurfaceKey,
  hrGeoGeofencesSearchParam,
  hrGeoPoliciesSurfaceKey,
  hrGeoPoliciesSearchParam,
  hrGeoDevicesSurfaceKey,
  hrGeoDevicesSearchParam,
  hrGeoPendingSurfaceKey,
  hrGeoPendingSearchParam,
  hrGeoHistorySurfaceKey,
  hrGeoHistorySearchParam,
  hrGeoReportsSurfaceKey,
  hrGeoStatsSurfaceKey,
  hrGeoAuditTrailSurfaceKey,
  hrGeoLamExposureSurfaceKey,
  hrGeoOvertimeRefSurfaceKey,
  hrGeoPayrollRefSurfaceKey,
  hrGeoRawVsApprovedSurfaceKey,
  hrGeoReportGroupByParam,
  hrGeoUiCopy,
  buildHrGeoAuditTrailListSurface,
  buildHrGeoLamExposureListSurface,
  buildHrGeoOvertimeReferenceListSurface,
  buildHrGeoPayrollReferenceListSurface,
  buildHrGeoRawVsApprovedListSurface,
  parseHrGeoSearchParams,
  toHrGeoPageModelInput,
  type HrGeoSearchParams,
  type HrGeoPageModelInput,
  type HrGeoListSurfaceKey,
  hrGeoRoutePaths,
  type HrGeoRoutePath,
  assertGeoCoverageComplete,
  GEO_REQUIREMENT_COVERAGE,
  GEO_SPEC_MAP,
  GEO_REQUIREMENT_CODES,
} from "./time-attendance/geolocation-remote-checkin/metadata";

export {
  getHrLamListSurfaceKeys,
  HR_LAM_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_LAM_LIST_SEARCH_PARAMS_BY_KEY,
  HR_LAM_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_LAM_LIST_SURFACE_KEYS,
  HR_LAM_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrLamAttendanceDaysSurfaceKey,
  hrLamAttendanceDaysSearchParam,
  hrLamLeaveRequestsSurfaceKey,
  hrLamLeaveRequestsSearchParam,
  hrLamLeaveBalancesSurfaceKey,
  hrLamLeaveBalancesSearchParam,
  hrLamUiCopy,
  parseHrLamSearchParams,
  toHrLamPageModelInput,
  type HrLamSearchParams,
  type HrLamListSurfaceKey,
  hrLamRoutePaths,
  type HrLamRoutePath,
} from "./time-attendance/leave-attendance-management/metadata";

/** @deprecated Use hrLamUiCopy */
export { hrLamUiCopy as hrLeaveAttendanceUiCopy } from "./time-attendance/leave-attendance-management/metadata";

export {
  getHrLifecycleListSurfaceKeys,
  HR_LIFECYCLE_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_LIFECYCLE_LIST_SEARCH_PARAMS_BY_KEY,
  HR_LIFECYCLE_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_LIFECYCLE_LIST_SURFACE_KEYS,
  HR_LIFECYCLE_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrLifecycleOverviewSurfaceKey,
  hrLifecyclePendingTransitionsSurfaceKey,
  hrLifecyclePendingTransitionsSearchParam,
  hrLifecycleProbationDueSurfaceKey,
  hrLifecycleProbationDueSearchParam,
  hrLifecycleAuditTrailSurfaceKey,
  hrLifecycleAuditTrailSearchParam,
  hrLifecycleOnboardingCasesSurfaceKey,
  hrLifecycleOnboardingCasesSearchParam,
  hrLifecycleNoticePeriodSurfaceKey,
  hrLifecycleNoticePeriodSearchParam,
  hrLifecycleOffboardingCasesSurfaceKey,
  hrLifecycleOffboardingCasesSearchParam,
  hrLifecycleUiCopy,
  parseHrLifecycleSearchParams,
  toHrLifecyclePageModelInput,
  type HrLifecycleSearchParams,
  type HrLifecycleListSurfaceKey,
  hrLifecycleOverviewSearchParam,
  hrLifecycleEmploymentStatusFilterParam,
} from "./employee-management/employee-lifecycle-management/metadata";

export {
  hrLifecycleRoutePaths,
  type HrLifecycleRoutePath,
} from "./employee-management/employee-lifecycle-management/contracts/hr.workforce.lifecycle-route.contract";

export {
  getHrOffboardingListSurfaceKeys,
  HR_OFFBOARDING_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_OFFBOARDING_LIST_SEARCH_PARAMS_BY_KEY,
  HR_OFFBOARDING_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_OFFBOARDING_LIST_SURFACE_KEYS,
  HR_OFFBOARDING_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrOffboardingCasesSurfaceKey,
  hrOffboardingCasesSearchParam,
  hrOffboardingClearanceSurfaceKey,
  hrOffboardingClearanceSearchParam,
  hrOffboardingUiCopy,
  parseHrOffboardingSearchParams,
  toHrOffboardingPageModelInput,
  type HrOffboardingSearchParams,
  type HrOffboardingListSurfaceKey,
} from "./employee-management/offboarding-exit-management/metadata";

export {
  hrOffboardingRoutePaths,
  type HrOffboardingRoutePath,
} from "./employee-management/offboarding-exit-management/contracts/hr.workforce.offboarding-route.contract";

export {
  getHrBenefitsListSurfaceKeys,
  HR_BENEFITS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_BENEFITS_LIST_SEARCH_PARAMS_BY_KEY,
  HR_BENEFITS_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_BENEFITS_LIST_SURFACE_KEYS,
  HR_BENEFITS_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrBenefitsAuditTrailSearchParam,
  hrBenefitsAuditTrailSurfaceKey,
  hrBenefitsEligibilityRulesSearchParam,
  hrBenefitsEligibilityRulesSurfaceKey,
  hrBenefitsEnrollmentsSearchParam,
  hrBenefitsEnrollmentsSurfaceKey,
  hrBenefitsOpenEnrollmentSearchParam,
  hrBenefitsOpenEnrollmentSurfaceKey,
  hrBenefitsPlansSearchParam,
  hrBenefitsPlansSurfaceKey,
  hrBenefitsProvidersSearchParam,
  hrBenefitsProvidersSurfaceKey,
  hrBenefitsUiCopy,
  parseHrBenefitsSearchParams,
  toHrBenefitsPageModelInput,
  type HrBenefitsSearchParams,
  type HrBenefitsListSurfaceKey,
} from "./payroll-compensation/benefits-administration/metadata";

export {
  hrBenefitsRoutePaths,
  type HrBenefitsRoutePath,
} from "./payroll-compensation/benefits-administration/contracts/hr.payroll.benefits-route.contract";

export {
  getHrBonusListSurfaceKeys,
  HR_BONUS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_BONUS_LIST_SEARCH_PARAMS_BY_KEY,
  HR_BONUS_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_BONUS_LIST_SURFACE_KEYS,
  hrBonusPlansSearchParam,
  hrBonusPlansSurfaceKey,
  hrBonusEligibilityRulesSearchParam,
  hrBonusEligibilityRulesSurfaceKey,
  hrBonusParticipantsSearchParam,
  hrBonusParticipantsSurfaceKey,
  hrBonusCyclesSearchParam,
  hrBonusCyclesSurfaceKey,
  hrBonusTargetsSearchParam,
  hrBonusTargetsSurfaceKey,
  hrBonusDiscretionarySearchParam,
  hrBonusDiscretionarySurfaceKey,
  hrBonusGuaranteedRulesSearchParam,
  hrBonusGuaranteedRulesSurfaceKey,
  hrBonusManualAdjustmentsSearchParam,
  hrBonusManualAdjustmentsSurfaceKey,
  hrBonusMultipliersSearchParam,
  hrBonusMultipliersSurfaceKey,
  hrBonusProrationsSearchParam,
  hrBonusProrationsSurfaceKey,
  hrBonusRecoveriesSearchParam,
  hrBonusRecoveriesSurfaceKey,
  hrBonusUiCopy,
  parseHrBonusSearchParams,
  toHrBonusPageModelInput,
  type HrBonusSearchParams,
  type HrBonusListSurfaceKey,
} from "./payroll-compensation/bonus-incentive-management/metadata";

export {
  hrBonusRoutePaths,
  type HrBonusRoutePath,
} from "./payroll-compensation/bonus-incentive-management/contracts/hr.payroll.bonus-route.contract";

export {
  getHrExpenseListSurfaceKeys,
  HR_EXPENSE_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_EXPENSE_LIST_SEARCH_PARAMS_BY_KEY,
  HR_EXPENSE_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_EXPENSE_LIST_SURFACE_KEYS,
  HR_EXPENSE_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrExpenseAuditTrailSearchParam,
  hrExpenseAuditTrailSurfaceKey,
  hrExpenseClaimsSearchParam,
  hrExpenseClaimsSurfaceKey,
  hrExpenseReportsSearchParam,
  hrExpenseReportsSurfaceKey,
  hrExpenseUiCopy,
  parseHrExpenseSearchParams,
  toHrExpensePageModelInput,
  type HrExpenseSearchParams,
  type HrExpenseListSurfaceKey,
} from "./payroll-compensation/expenses-reimbursement/metadata";

export {
  hrExpenseRoutePaths,
  type HrExpenseRoutePath,
} from "./payroll-compensation/expenses-reimbursement/contracts/hr.payroll.expense-route.contract";

export {
  getHrCpmListSurfaceKeys,
  HR_CPM_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_CPM_LIST_SURFACE_KEYS,
  hrCpmAuditSearchParam,
  hrCpmAuditSurfaceKey,
  hrCpmCyclesSearchParam,
  hrCpmCyclesSurfaceKey,
  hrCpmParticipantsSearchParam,
  hrCpmParticipantsSurfaceKey,
  hrCpmRecommendationsSearchParam,
  hrCpmRecommendationsSurfaceKey,
  hrCpmReportsSearchParam,
  hrCpmReportsSurfaceKey,
  hrCpmUiCopy,
  parseHrCpmSearchParams,
  toHrCpmAuditPageModelInput,
  toHrCpmCycleDetailPageModelInput,
  toHrCpmHubPageModelInput,
  toHrCpmReportsPageModelInput,
  hrCpmRoutePaths,
  hrCpmCycleDetailRoutePath,
  type HrCpmRoutePath,
  type HrCpmListSurfaceKey,
  type HrCpmSearchParams,
} from "./payroll-compensation/compensation-planning-modeling/metadata";

export {
  getHrCsfListSurfaceKeys,
  HR_CSF_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_CSF_LIST_SURFACE_KEYS,
  hrCsfAuditSearchParam,
  hrCsfAuditSurfaceKey,
  hrCsfCompetenciesSearchParam,
  hrCsfCompetenciesSurfaceKey,
  hrCsfGapsSearchParam,
  hrCsfGapsSurfaceKey,
  hrCsfMatchTargetCodeParam,
  hrCsfMatchTargetKindParam,
  hrCsfMatchingSearchParam,
  hrCsfMatchingSurfaceKey,
  hrCsfReportGroupByParam,
  hrCsfReportsSearchParam,
  hrCsfReportsSurfaceKey,
  hrCsfRoutePaths,
  hrCsfSkillsSearchParam,
  hrCsfSkillsSurfaceKey,
  hrCsfUiCopy,
  parseHrCsfSearchParams,
  toHrCsfAuditPageModelInput,
  toHrCsfHubPageModelInput,
  toHrCsfMatchingPageModelInput,
  toHrCsfReportsPageModelInput,
  type HrCsfListSurfaceKey,
  type HrCsfRoutePath,
  type HrCsfSearchParams,
} from "./talent-management/competency-skills-framework/metadata";

export {
  getHrMcpListSurfaceKeys,
  HR_MCP_LIST_SURFACE_COLUMNS_BY_KEY,
  hrMcpAuditTrailSearchParam,
  hrMcpAuditTrailSurfaceKey,
  hrMcpCountryConfigIdParam,
  hrMcpCountryConfigsSearchParam,
  hrMcpCountryConfigsSurfaceKey,
  hrMcpCrossCountryCostSearchParam,
  hrMcpCrossCountryCostSurfaceKey,
  hrMcpPeriodRefParam,
  hrMcpRuleVersionsSearchParam,
  hrMcpRuleVersionsSurfaceKey,
  hrMcpUiCopy,
  parseHrMcpSearchParams,
  toHrMcpAuditPageModelInput,
  toHrMcpCountryDetailPageModelInput,
  toHrMcpCrossCountryReportsPageModelInput,
  toHrMcpHubPageModelInput,
  hrMcpRoutePaths,
  type HrMcpRoutePath,
  type HrMcpListSurfaceKey,
  type HrMcpSearchParams,
} from "./payroll-compensation/multi-country-payroll/metadata";

export {
  getHrSbsListSurfaceKeys,
  HR_SBS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_SBS_LIST_SURFACE_KEYS,
  hrSbsAnalysesSearchParam,
  hrSbsAnalysesSurfaceKey,
  hrSbsAuditSearchParam,
  hrSbsAuditSurfaceKey,
  hrSbsBenchmarkReportSearchParam,
  hrSbsBenchmarkReportSurfaceKey,
  hrSbsMappingsSearchParam,
  hrSbsMappingsSurfaceKey,
  hrSbsPayEquityReportSearchParam,
  hrSbsPayEquityReportSurfaceKey,
  hrSbsVersionsSearchParam,
  hrSbsVersionsSurfaceKey,
  hrSbsUiCopy,
  parseHrSbsSearchParams,
  toHrSbsAuditPageModelInput,
  toHrSbsHubPageModelInput,
  toHrSbsReportsPageModelInput,
  hrSbsRoutePaths,
  type HrSbsRoutePath,
  type HrSbsListSurfaceKey,
  type HrSbsSearchParams,
} from "./payroll-compensation/salary-benchmarking-survey/metadata";

export {
  getHrPayrollListSurfaceKeys,
  HR_PAYROLL_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_PAYROLL_LIST_SEARCH_PARAMS_BY_KEY,
  HR_PAYROLL_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_PAYROLL_LIST_SURFACE_KEYS,
  HR_PAYROLL_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrPayrollAuditSearchParam,
  hrPayrollAuditSurfaceKey,
  hrPayrollAssignmentsSearchParam,
  hrPayrollAssignmentsSurfaceKey,
  hrPayrollCyclesSearchParam,
  hrPayrollCyclesSurfaceKey,
  hrPayrollPayGroupsSearchParam,
  hrPayrollPayGroupsSurfaceKey,
  hrPayrollPaymentsSearchParam,
  hrPayrollPaymentsSurfaceKey,
  hrPayrollPayslipsSearchParam,
  hrPayrollPayslipsSurfaceKey,
  hrPayrollRunsSearchParam,
  hrPayrollRunsSurfaceKey,
  hrPayrollUiCopy,
  parseHrPayrollSearchParams,
  toHrPayrollPageModelInput,
  toHrPayrollAuditPageModelInput,
  hrPayrollProcessingRoutePaths,
  hrPayrollRunDetailRoutePath,
  type HrPayrollProcessingRoutePath,
  type HrPayrollListSurfaceKey,
  type HrPayrollSearchParams,
  PAYROLL_REQUIREMENT_COVERAGE,
  PAYROLL_ACCEPTANCE_CRITERIA_COVERAGE,
} from "./payroll-compensation/payroll-processing/metadata";

export {
  getHrAatListSurfaceKeys,
  HR_AAT_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_AAT_LIST_SEARCH_PARAMS_BY_KEY,
  HR_AAT_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_AAT_LIST_SURFACE_KEYS,
  HR_AAT_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrAatAuditTrailSearchParam,
  hrAatAuditTrailSurfaceKey,
  hrAatNotificationsSearchParam,
  hrAatNotificationsSurfaceKey,
  hrAatRiskIndicatorsSearchParam,
  hrAatRiskIndicatorsSurfaceKey,
  hrAatSnapshotsSearchParam,
  hrAatSnapshotsSurfaceKey,
  hrAatOverviewStatSurfaceKey,
  hrAatUiCopy,
  parseHrAatSearchParams,
  toHrAatPageModelInput,
  type HrAatSearchParams,
  type HrAatListSurfaceKey,
  hrAatRoutePaths,
  type HrAatRoutePath,
} from "./time-attendance/absence-analytics-trends/metadata";

export const hrOnboardingUiCopy = {
  page: {
    title: "Onboarding",
    description: "Onboarding is managed by HR Suite.",
  } satisfies HrUiCopyPage,
};

export const hrOvertimeUiCopy = {
  page: {
    title: "Overtime",
    description: "Overtime is managed by HR Suite.",
  } satisfies HrUiCopyPage,
};

export const hrShiftsUiCopy = {
  page: {
    title: "Shift Scheduling",
    description:
      "Manage shift rosters, compare attendance, payroll references, reports, and audit history.",
  } satisfies HrUiCopyPage,
};

export {
  getHrSftListSurfaceKeys,
  getHrSftArchitectureSurfaceKeys,
  HR_SFT_ARCHITECTURE_SURFACE_KEYS,
  HR_SFT_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_SFT_LIST_SEARCH_PARAMS_BY_KEY,
  HR_SFT_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_SFT_LIST_SURFACE_KEYS,
  HR_SFT_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrSftAuditTrailSearchParam,
  hrSftAuditTrailSurfaceKey,
  hrSftAvailabilitySearchParam,
  hrSftCoverageSearchParam,
  hrSftMyScheduleChangesSearchParam,
  hrSftMySwapsSearchParam,
  hrSftNotificationsSearchParam,
  hrSftNotificationsSurfaceKey,
  hrSftAttendanceReconcileSearchParam,
  hrSftAttendanceReconcileSurfaceKey,
  hrSftPayrollRefsSearchParam,
  hrSftPayrollRefsSurfaceKey,
  hrSftPublicationsSearchParam,
  hrSftPublicationsSurfaceKey,
  hrSftRecurrenceRulesSearchParam,
  hrSftReportDefinitionsSearchParam,
  hrSftReportDefinitionsSurfaceKey,
  hrSftRosterSearchParam,
  hrSftScheduleChangePendingSearchParam,
  hrSftSwapPendingSearchParam,
  hrSftTemplatesSearchParam,
  hrTimeSftAvailabilitySurfaceKey,
  hrTimeSftCoverageSurfaceKey,
  hrTimeSftMyScheduleChangesSurfaceKey,
  hrTimeSftMySwapsSurfaceKey,
  hrTimeSftRecurrenceRulesSurfaceKey,
  hrTimeSftRosterSurfaceKey,
  hrTimeSftScheduleChangePendingSurfaceKey,
  hrTimeSftSwapPendingSurfaceKey,
  hrTimeSftTemplatesSurfaceKey,
  hrSftUiCopy,
  parseHrSftSearchParams,
  toHrSftPageModelInput,
  toHrSftSelfServicePageModelInput,
  type HrSftSearchParams,
  type HrSftListSurfaceKey,
  type HrSftArchitectureSurfaceKey,
  hrSftRoutePaths,
  type HrSftRoutePath,
  HR_TIME_SFT_ARCHITECTURE_SURFACE_KEYS,
  type HrTimeSftArchitectureSurfaceKey,
  assertSftFoundationCoverageComplete,
  assertSftConflictPolicyCoverageComplete,
  assertSftWorkflowCoverageComplete,
  assertSftIntegrationCoverageComplete,
  assertSftRequirementCoverageComplete,
  SFT_REQUIREMENT_COVERAGE,
} from "./time-attendance/shift-scheduling/metadata";

export {
  getHrTimeClockListSurfaceKeys,
  HR_TIME_CLOCK_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_TIME_CLOCK_LIST_SEARCH_PARAMS_BY_KEY,
  HR_TIME_CLOCK_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_TIME_CLOCK_LIST_SURFACE_KEYS,
  HR_TIME_CLOCK_SEARCH_PARAM_TO_PAGE_MODEL_FIELD,
  hrTimeClockDevicesSurfaceKey,
  hrTimeClockDevicesSearchParam,
  hrTimeClockEmployeeMappingsSurfaceKey,
  hrTimeClockEmployeeMappingsSearchParam,
  hrTimeClockRawPunchesSurfaceKey,
  hrTimeClockRawPunchesSearchParam,
  hrTimeClockPunchExceptionsSurfaceKey,
  hrTimeClockPunchExceptionsSearchParam,
  hrTimeClockSyncBatchesSurfaceKey,
  hrTimeClockSyncBatchesSearchParam,
  hrTimeClockAuditTrailSurfaceKey,
  hrTimeClockAuditTrailSearchParam,
  hrTimeClockReportsSurfaceKey,
  hrTimeClockReportGroupByParam,
  hrTimeClockOverviewStatSurfaceKey,
  hrTimeClockLamExportSurfaceKey,
  hrTimeClockLamExportSearchParam,
  hrTimeClockOvertimeRefsSurfaceKey,
  hrTimeClockOvertimeRefsSearchParam,
  hrTimeClockPayrollRefsSurfaceKey,
  hrTimeClockPayrollRefsSearchParam,
  hrTimeClockUiCopy,
  parseHrTimeClockSearchParams,
  toHrTimeClockPageModelInput,
  type HrTimeClockSearchParams,
  type HrTimeClockListSurfaceKey,
  hrTimeClockRoutePaths,
  type HrTimeClockRoutePath,
} from "./time-attendance/time-clock-integration/metadata";
export {
  hrLmsUiCopy,
  hrLmsCoursesSurfaceKey,
  hrLmsEmployeeOverviewSurfaceKey,
  hrLmsManagerOverviewSurfaceKey,
  hrLmsAdminOverviewSurfaceKey,
  hrLmsReportsSurfaceKey,
  hrLmsAuditSurfaceKey,
} from "./talent-management/learning-management-system-lms/metadata";

export {
  getHrPerformanceAppraisalsListSurfaceKeys,
  HR_PERFORMANCE_APPRAISALS_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_PERFORMANCE_APPRAISALS_LIST_SEARCH_PARAMS_BY_KEY,
  HR_PERFORMANCE_APPRAISALS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_PERFORMANCE_APPRAISALS_LIST_SURFACE_KEYS,
  HR_PERFORMANCE_APPRAISALS_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrPerformanceAppraisalsApprovalsSearchParam,
  hrPerformanceAppraisalsApprovalsSurfaceKey,
  hrPerformanceAppraisalsAuditTrailSearchParam,
  hrPerformanceAppraisalsAuditTrailSurfaceKey,
  hrPerformanceAppraisalsCyclesSearchParam,
  hrPerformanceAppraisalsCyclesSurfaceKey,
  hrPerformanceAppraisalsGoalsSearchParam,
  hrPerformanceAppraisalsGoalsSurfaceKey,
  hrPerformanceAppraisalsOutcomesSearchParam,
  hrPerformanceAppraisalsOutcomesSurfaceKey,
  hrPerformanceAppraisalsReportGroupByParam,
  hrPerformanceAppraisalsReportsSearchParam,
  hrPerformanceAppraisalsReportsSurfaceKey,
  hrPerformanceAppraisalsReviewsSearchParam,
  hrPerformanceAppraisalsReviewsSurfaceKey,
  hrPerformanceAppraisalsUiCopy,
  hrPerformanceRoutePaths,
  parseHrPerformanceAppraisalsSearchParams,
  toHrPerformanceAppraisalsPageModelInput,
  type HrPerformanceAppraisalsListSurfaceKey,
  type HrPerformanceAppraisalsPageModelInput,
  type HrPerformanceAppraisalsSearchParams,
  type HrPerformanceRoutePath,
} from "./talent-management/performance-appraisals/metadata";

export {
  getHrRonListSurfaceKeys,
  HR_RON_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_RON_LIST_SEARCH_PARAMS_BY_KEY,
  HR_RON_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_RON_LIST_SURFACE_KEYS,
  HR_RON_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrRonApplicationDetailRoutePath,
  hrRonApplicationsSearchParam,
  hrRonApplicationsSurfaceKey,
  hrRonAuditTrailSearchParam,
  hrRonAuditTrailSurfaceKey,
  hrRonInterviewsSearchParam,
  hrRonInterviewsSurfaceKey,
  hrRonOfferDetailRoutePath,
  hrRonOffersSearchParam,
  hrRonOffersSurfaceKey,
  hrRonOnboardingTasksSearchParam,
  hrRonOnboardingTasksSurfaceKey,
  hrRonPostingsSearchParam,
  hrRonPostingsSurfaceKey,
  hrRonReadinessSearchParam,
  hrRonReadinessSurfaceKey,
  hrRonReportGroupByParam,
  hrRonReportsSearchParam,
  hrRonReportsSurfaceKey,
  hrRonRequisitionDetailRoutePath,
  hrRonRequisitionsSearchParam,
  hrRonRequisitionsSurfaceKey,
  hrRonRoutePaths,
  hrRonUiCopy,
  parseHrRonSearchParams,
  toHrRonPageModelInput,
  type HrRonListSurfaceKey,
  type HrRonRoutePath,
  type HrRonSearchParams,
} from "./talent-management/recruitment-onboarding/metadata";

export {
  getHrSuccessionListSurfaceKeys,
  getHrSuccessionPlanningListSurfaceKeys,
  HR_SUCCESSION_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_SUCCESSION_LIST_SEARCH_PARAMS_BY_KEY,
  HR_SUCCESSION_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_SUCCESSION_LIST_SURFACE_KEYS,
  HR_SUCCESSION_WORKBENCH_READ_ONLY_SURFACE_KEYS,
  hrSuccessionAuditTrailSearchParam,
  hrSuccessionAuditTrailSurfaceKey,
  hrSuccessionBenchStrengthSearchParam,
  hrSuccessionBenchStrengthSurfaceKey,
  hrSuccessionCalibrationReviewsSearchParam,
  hrSuccessionCalibrationReviewsSurfaceKey,
  hrSuccessionCompetencyGapsSearchParam,
  hrSuccessionCompetencyGapsSurfaceKey,
  hrSuccessionCriticalRoleDetailRoutePath,
  hrSuccessionCriticalRolesSearchParam,
  hrSuccessionCriticalRolesSurfaceKey,
  hrSuccessionDevelopmentPlansSearchParam,
  hrSuccessionDevelopmentPlansSurfaceKey,
  hrSuccessionLifecycleRecommendationsSearchParam,
  hrSuccessionLifecycleRecommendationsSurfaceKey,
  hrSuccessionNotificationsSearchParam,
  hrSuccessionNotificationsSurfaceKey,
  hrSuccessionOverviewKpiSurfaceKey,
  hrSuccessionPlanningRoutePaths,
  hrSuccessionPlanningUiCopy,
  hrSuccessionReplacementPlansSearchParam,
  hrSuccessionReplacementPlansSurfaceKey,
  hrSuccessionReportGroupByParam,
  hrSuccessionReportsSearchParam,
  hrSuccessionReportsSurfaceKey,
  hrSuccessionSuccessorDetailRoutePath,
  hrSuccessionSuccessorsSearchParam,
  hrSuccessionSuccessorsSurfaceKey,
  hrSuccessionTalentPoolsSearchParam,
  hrSuccessionTalentPoolsSurfaceKey,
  hrSuccessionUiCopy,
  hrTalentSuccessionUiCopy,
  hrSuccessionRoutePaths,
  parseHrSuccessionSearchParams,
  toHrSuccessionPageModelInput,
  parseHrSuccessionPlanningSearchParams,
  toHrSuccessionPlanningPageModelInput,
  SUCCESSION_ACCEPTANCE_CRITERIA_COVERAGE,
  SUCCESSION_REQUIREMENT_COVERAGE,
  assertSuccessionAcceptanceCriteriaComplete,
  assertSuccessionCoverageComplete,
  type HrSuccessionListSurfaceKey,
  type HrSuccessionPageModelInput,
  type HrSuccessionPlanningRoutePath,
  type HrSuccessionRoutePath,
  type HrSuccessionSearchParams,
} from "./talent-management/succession-planning/metadata";

export {
  assertHrTalentTrainingEnterpriseCoverage,
  assertHrTrainingEnterpriseCoverage,
  getHrTalentTrainingListSurfaceKeys,
  getHrTrainingListSurfaceKeys,
  HR_TALENT_TRAINING_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_TALENT_TRAINING_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_TALENT_TRAINING_LIST_SEARCH_PARAMS_BY_KEY,
  HR_TALENT_TRAINING_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_TALENT_TRAINING_LIST_SURFACE_KEYS,
  HR_TALENT_TRAINING_READ_ONLY_LIST_SURFACE_KEYS,
  HR_TALENT_TRAINING_REQUIREMENT_COVERAGE,
  HR_TRAINING_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_TRAINING_LIST_SEARCH_PARAMS_BY_KEY,
  HR_TRAINING_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_TRAINING_LIST_SURFACE_KEYS,
  HR_TRAINING_READ_ONLY_LIST_SURFACE_KEYS,
  hrTalentTrainingRoutePaths,
  hrTalentTrainingUiCopy,
  hrTrainingAuditTrailSurfaceKey,
  hrTrainingCoursesSurfaceKey,
  hrTrainingOverviewKpiSurfaceKey,
  hrTrainingRoutePaths,
  hrTrainingUiCopy,
  parseHrTalentTrainingSearchParams,
  parseHrTrainingSearchParams,
  toHrTalentTrainingPageModelInput,
  toHrTrainingPageModelInput,
  type HrTalentTrainingListSurfaceKey,
  type HrTalentTrainingPageModelInput,
  type HrTalentTrainingRoutePath,
  type HrTalentTrainingSearchParams,
  type HrTrainingListSurfaceKey,
  type HrTrainingPageModelInput,
  type HrTrainingRoutePath,
  type HrTrainingSearchParams,
} from "./talent-management/training-development/metadata";

export {
  assertHrIndustryFrmEnterpriseCoverage,
  getHrIndustryFrmListSurfaceKeys,
  HR_INDUSTRY_FRM_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_INDUSTRY_FRM_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_INDUSTRY_FRM_LIST_SEARCH_PARAMS_BY_KEY,
  HR_INDUSTRY_FRM_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_INDUSTRY_FRM_LIST_SURFACE_KEYS,
  HR_INDUSTRY_FRM_READ_ONLY_LIST_SURFACE_KEYS,
  HR_INDUSTRY_FRM_REQUIREMENT_COVERAGE,
  hrIndustryFrmAssignmentsSurfaceKey,
  hrIndustryFrmAuditTrailSurfaceKey,
  hrIndustryFrmOverviewKpiSurfaceKey,
  hrIndustryFrmRoutePaths,
  hrIndustryFrmUiCopy,
  parseHrIndustryFrmSearchParams,
  toHrIndustryFrmPageModelInput,
  type HrIndustryFrmListSurfaceKey,
  type HrIndustryFrmPageModelInput,
  type HrIndustryFrmRoutePath,
  type HrIndustryFrmSearchParams,
} from "./industry-specific/field-worker-remote-workforce-management/metadata";

export {
  assertHrIndustryFhcEnterpriseCoverage,
  getHrIndustryFhcListSurfaceKeys,
  HR_INDUSTRY_FHC_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_INDUSTRY_FHC_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_INDUSTRY_FHC_LIST_SEARCH_PARAMS_BY_KEY,
  HR_INDUSTRY_FHC_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_INDUSTRY_FHC_LIST_SURFACE_KEYS,
  HR_INDUSTRY_FHC_READ_ONLY_LIST_SURFACE_KEYS,
  HR_INDUSTRY_FHC_REQUIREMENT_COVERAGE,
  hrIndustryFhcAlertsSurfaceKey,
  hrIndustryFhcAuditTrailSurfaceKey,
  hrIndustryFhcEmployeeComplianceSurfaceKey,
  hrIndustryFhcOverviewKpiSurfaceKey,
  hrIndustryFhcRoutePaths,
  hrIndustryFhcUiCopy,
  parseHrIndustryFhcSearchParams,
  toHrIndustryFhcPageModelInput,
  type HrIndustryFhcListSurfaceKey,
  type HrIndustryFhcPageModelInput,
  type HrIndustryFhcRoutePath,
  type HrIndustryFhcSearchParams,
  type HrIndustryFhcStatusFilter,
} from "./industry-specific/food-handler-certification-health-compliance/metadata";

export {
  assertHrIndustryGpgEnterpriseCoverage,
  getHrIndustryGpgListSurfaceKeys,
  HR_INDUSTRY_GPG_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_INDUSTRY_GPG_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_INDUSTRY_GPG_LIST_SEARCH_PARAMS_BY_KEY,
  HR_INDUSTRY_GPG_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_INDUSTRY_GPG_LIST_SURFACE_KEYS,
  HR_INDUSTRY_GPG_READ_ONLY_LIST_SURFACE_KEYS,
  HR_INDUSTRY_GPG_REQUIREMENT_COVERAGE,
  hrIndustryGpgAuditTrailSurfaceKey,
  hrIndustryGpgClassificationAssignmentsSurfaceKey,
  hrIndustryGpgIntegrationExposuresSurfaceKey,
  hrIndustryGpgOverviewKpiSurfaceKey,
  hrIndustryGpgRoutePaths,
  hrIndustryGpgUiCopy,
  parseHrIndustryGpgSearchParams,
  toHrIndustryGpgPageModelInput,
  type HrIndustryGpgListSurfaceKey,
  type HrIndustryGpgPageModelInput,
  type HrIndustryGpgRoutePath,
  type HrIndustryGpgSearchParams,
  type HrIndustryGpgStatusFilter,
} from "./industry-specific/government-classification-pay-grades/metadata";

export {
  assertHrIndustryMscEnterpriseCoverage,
  getHrIndustryMscListSurfaceKeys,
  HR_INDUSTRY_MSC_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_INDUSTRY_MSC_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_INDUSTRY_MSC_LIST_SEARCH_PARAMS_BY_KEY,
  HR_INDUSTRY_MSC_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_INDUSTRY_MSC_LIST_SURFACE_KEYS,
  HR_INDUSTRY_MSC_READ_ONLY_LIST_SURFACE_KEYS,
  HR_INDUSTRY_MSC_REQUIREMENT_COVERAGE,
  hrIndustryMscAuditTrailSurfaceKey,
  hrIndustryMscEmployeeObligationsSurfaceKey,
  hrIndustryMscIntegrationExposuresSurfaceKey,
  hrIndustryMscOverviewKpiSurfaceKey,
  hrIndustryMscRoutePaths,
  hrIndustryMscUiCopy,
  parseHrIndustryMscSearchParams,
  toHrIndustryMscPageModelInput,
  type HrIndustryMscListSurfaceKey,
  type HrIndustryMscPageModelInput,
  type HrIndustryMscRoutePath,
  type HrIndustryMscSearchParams,
  type HrIndustryMscStatusFilter,
} from "./industry-specific/manufacturing-safety-training-osha-compliance/metadata";

export {
  assertHrIndustryRwsEnterpriseCoverage,
  getHrIndustryRwsListSurfaceKeys,
  HR_INDUSTRY_RWS_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_INDUSTRY_RWS_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_INDUSTRY_RWS_LIST_SEARCH_PARAMS_BY_KEY,
  HR_INDUSTRY_RWS_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_INDUSTRY_RWS_LIST_SURFACE_KEYS,
  HR_INDUSTRY_RWS_READ_ONLY_LIST_SURFACE_KEYS,
  HR_INDUSTRY_RWS_REQUIREMENT_COVERAGE,
  hrIndustryRwsAssignmentsSurfaceKey,
  hrIndustryRwsAuditTrailSurfaceKey,
  hrIndustryRwsIntegrationExposuresSurfaceKey,
  hrIndustryRwsOverviewKpiSurfaceKey,
  hrIndustryRwsRoutePaths,
  hrIndustryRwsUiCopy,
  parseHrIndustryRwsSearchParams,
  toHrIndustryRwsPageModelInput,
  type HrIndustryRwsListSurfaceKey,
  type HrIndustryRwsPageModelInput,
  type HrIndustryRwsRoutePath,
  type HrIndustryRwsSearchParams,
  type HrIndustryRwsStatusFilter,
} from "./industry-specific/retail-seasonal-hourly-workforce-scheduling/metadata";

export {
  assertHrIndustryUcbEnterpriseCoverage,
  getHrIndustryUcbListSurfaceKeys,
  HR_INDUSTRY_UCB_ACCEPTANCE_CRITERIA_COVERAGE,
  HR_INDUSTRY_UCB_LIST_SEARCH_PARAM_MODEL_FIELDS,
  HR_INDUSTRY_UCB_LIST_SEARCH_PARAMS_BY_KEY,
  HR_INDUSTRY_UCB_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_INDUSTRY_UCB_LIST_SURFACE_KEYS,
  HR_INDUSTRY_UCB_READ_ONLY_LIST_SURFACE_KEYS,
  HR_INDUSTRY_UCB_REQUIREMENT_COVERAGE,
  hrIndustryUcbAgreementsSurfaceKey,
  hrIndustryUcbAuditTrailSurfaceKey,
  hrIndustryUcbGrievancesSurfaceKey,
  hrIndustryUcbIntegrationExposuresSurfaceKey,
  hrIndustryUcbMembershipsSurfaceKey,
  hrIndustryUcbOverviewKpiSurfaceKey,
  hrIndustryUcbRoutePaths,
  hrIndustryUcbUiCopy,
  parseHrIndustryUcbSearchParams,
  toHrIndustryUcbPageModelInput,
  type HrIndustryUcbListSurfaceKey,
  type HrIndustryUcbPageModelInput,
  type HrIndustryUcbRoutePath,
  type HrIndustryUcbSearchParams,
  type HrIndustryUcbStatusFilter,
} from "./industry-specific/union-management/metadata";

export {
  HR_CAREER_PATHING_LIST_SURFACE_KEYS,
  hrCareerPathingReadinessSurfaceKey,
  hrCareerPathingReportsSurfaceKey,
  hrCareerPathingAuditSurfaceKey,
  hrCareerPathingReadinessSearchParam,
  hrCareerPathingReportsSearchParam,
  hrCareerPathingAuditSearchParam,
  hrCareerPathingReportGroupByParam,
  parseHrCareerPathingSearchParams,
  getHrCareerPathingListSurfaceKeys,
  HR_CAREER_PATHING_LIST_SURFACE_COLUMNS_BY_KEY,
  HR_CAREER_READINESS_LEVELS,
  HR_CAREER_REPORT_GROUP_BY,
  CAREER_PATHING_REQUIREMENT_COVERAGE,
  CAREER_PATHING_ACCEPTANCE_CRITERIA_COVERAGE,
  assertCareerPathingCoverageComplete,
  assertCareerPathingAcceptanceCriteriaComplete,
  hrCareerPathingUiCopy,
  hrTalentCareerPathingUiCopy,
  type HrCareerPathingListSurfaceKey,
  type HrCareerPathingSearchParams,
  type HrCareerReadinessLevel,
  type HrCareerReportGroupBy,
} from "./talent-management/career-pathing-development-plans/metadata";


export * from "./talent-management/candidate-selfservice-portal/metadata";