export const hrPayrollUiCopy = {
  page: {
    title: "Payroll Processing",
    description:
      "Calculate, validate, approve, and release employee pay across pay groups, cycles, and payroll runs.",
  },
  accessDenied: {
    title: "Access restricted",
    description: "You do not have permission to view payroll processing.",
  },
  nav: {
    hub: "Overview",
    audit: "Audit trail",
  },
  cycles: {
    surfaceHeaderTitle: "Payroll cycles",
    searchLabel: "Search cycles",
    searchPlaceholder: "Code or name",
    emptyTitle: "No payroll cycles",
    emptyDescription: "Create a payroll cycle for a pay group to begin processing.",
    colCode: "Code",
    colName: "Name",
    colStatus: "Status",
    colPeriodStart: "Period start",
    colPeriodEnd: "Period end",
    colPayDate: "Pay date",
    colCurrency: "Currency",
  },
  payGroups: {
    surfaceHeaderTitle: "Pay groups",
    searchLabel: "Search pay groups",
    searchPlaceholder: "Code or name",
    emptyTitle: "No pay groups",
    emptyDescription: "Define pay groups for monthly, weekly, or ad hoc schedules.",
    colCode: "Code",
    colName: "Name",
    colSchedule: "Schedule",
    colStatus: "Status",
    colCurrency: "Currency",
  },
  assignments: {
    surfaceHeaderTitle: "Employee assignments",
    searchLabel: "Search assignments",
    searchPlaceholder: "Employee number or name",
    emptyTitle: "No assignments",
    emptyDescription: "Assign employees to payroll groups before running payroll.",
    colEmployee: "Employee",
    colNumber: "Number",
    colStatus: "Status",
    colEffectiveFrom: "Effective from",
  },
  runs: {
    surfaceHeaderTitle: "Payroll runs",
    searchLabel: "Search runs",
    searchPlaceholder: "Run number or status",
    emptyTitle: "No payroll runs",
    emptyDescription: "Create a payroll run from a cycle to calculate pay.",
    colRunNumber: "Run #",
    colKind: "Kind",
    colStatus: "Status",
    colEmployees: "Employees",
    colNetPay: "Net pay",
    colFinalized: "Finalized",
  },
  payslips: {
    surfaceHeaderTitle: "Payslips",
    searchLabel: "Search payslips",
    searchPlaceholder: "Payslip number",
    emptyTitle: "No payslips",
    emptyDescription: "Payslips are generated after payroll finalization.",
    colNumber: "Payslip #",
    colEmployee: "Employee",
    colStatus: "Status",
    colNetPay: "Net pay",
    colEss: "ESS",
  },
  payments: {
    surfaceHeaderTitle: "Payment batches",
    searchLabel: "Search payments",
    searchPlaceholder: "Batch number",
    emptyTitle: "No payment batches",
    emptyDescription: "Generate payment batches after payroll is closed.",
    colBatch: "Batch",
    colStatus: "Status",
    colCount: "Payments",
    colAmount: "Total",
    colGenerated: "Generated",
  },
  audit: {
    pageTitle: "Payroll audit trail",
    pageDescription: "Every payroll calculation, adjustment, approval, and payment event.",
    surfaceHeaderTitle: "Audit events",
    searchLabel: "Search audit",
    searchPlaceholder: "Action or summary",
    emptyTitle: "No audit events",
    emptyDescription: "Payroll actions will appear here as they occur.",
    colAction: "Action",
    colSummary: "Summary",
    colOccurred: "Occurred",
    colActor: "Actor",
  },
} as const;
