export const systemAdminRoutePaths = {
  hub: "/system-admin",
  identity: "/system-admin/identity",
  users: "/system-admin/users",
  memberships: "/system-admin/memberships",
  roles: "/system-admin/roles",
  permissions: "/system-admin/permissions",
  modules: "/system-admin/modules",
  capabilities: "/system-admin/capabilities",
  policies: "/system-admin/policies",
  approvals: "/system-admin/approvals",
  audit: "/system-admin/audit",
  security: "/system-admin/security",
  organization: "/system-admin/organization",
  integrations: "/system-admin/integrations",
  lynx: "/system-admin/lynx",
  reliability: "/system-admin/reliability",
  billing: "/system-admin/billing",
  diagnostics: "/system-admin/diagnostics",
} as const;
