export const hrCpmUiCopy = {
  accessDenied: {
    title: "Compensation planning access denied",
    description:
      "You do not have permission to view compensation planning data for this organization.",
  },
  page: {
    title: "Compensation planning",
    description:
      "Plan merit, promotion, market, equity, and retention adjustments within budget pools and approval workflows.",
  },
  nav: {
    cycles: "Cycles",
    reports: "Reports",
    audit: "Audit trail",
  },
  cycles: {
    surfaceHeaderTitle: "Compensation cycles",
    searchLabel: "Search cycles",
    searchPlaceholder: "Search by code or name",
    emptyTitle: "No compensation cycles",
    emptyDescription: "Create a cycle to begin compensation planning.",
    colCode: "Code",
    colName: "Name",
    colType: "Type",
    colStatus: "Status",
    colEffective: "Effective",
    colCurrency: "Currency",
  },
  participants: {
    surfaceHeaderTitle: "Cycle participants",
    searchLabel: "Search participants",
    searchPlaceholder: "Search by employee or grade",
    emptyTitle: "No participants assigned",
    emptyDescription: "Assign eligible employees to this compensation cycle.",
    colEmployee: "Employee",
    colEligibility: "Eligibility",
    colSalary: "Current salary",
    colGrade: "Grade",
    colEntity: "Legal entity",
  },
  recommendations: {
    surfaceHeaderTitle: "Recommendations",
    searchLabel: "Search recommendations",
    searchPlaceholder: "Search by employee or adjustment type",
    emptyTitle: "No recommendations yet",
    emptyDescription:
      "Propose merit, promotion, market, equity, or retention adjustments for eligible participants.",
    colEmployee: "Employee",
    colType: "Adjustment",
    colStatus: "Status",
    colCurrent: "Current salary",
    colProposed: "Proposed salary",
    colFlags: "Flags",
    trailingActionsHeader: "Actions",
    trailingSubmitLabel: "Submit",
  },
  reports: {
    pageTitle: "Compensation planning reports",
    pageDescription:
      "Aggregate recommendations by department, manager, legal entity, grade, budget pool, and status.",
    surfaceHeaderTitle: "Planning report slices",
    searchLabel: "Search report rows",
    searchPlaceholder: "Filter by cycle, department, or status",
    emptyTitle: "No report rows",
    emptyDescription: "Report data appears after recommendations are recorded.",
    colCycle: "Cycle",
    colDepartment: "Department",
    colManager: "Manager",
    colEntity: "Legal entity",
    colGrade: "Grade",
    colPool: "Budget pool",
    colStatus: "Status",
    colCount: "Count",
  },
  audit: {
    pageTitle: "Compensation audit trail",
    pageDescription: "Immutable audit events for compensation planning actions.",
    surfaceHeaderTitle: "Audit events",
    searchLabel: "Search audit trail",
    searchPlaceholder: "Search by action or summary",
    emptyTitle: "No audit events",
    emptyDescription: "Audit events appear as compensation planning actions occur.",
    colOccurred: "Occurred",
    colAction: "Action",
    colSummary: "Summary",
    colActor: "Actor",
    colCycle: "Cycle",
  },
  cycleDetail: {
    backLabel: "Back to cycles",
  },
  participantContext: {
    sectionTitle: "Current compensation",
    sectionDescription:
      "Salary, grade, job level, department, manager, and salary effective date (HRM-CPM-006).",
    groupLabel: "Employee snapshot",
  },
  salaryBand: {
    sectionTitle: "Salary structure reference",
    sectionDescription:
      "Salary band minimum, midpoint, maximum, and range position where configured (HRM-CPM-007).",
    groupLabel: "Salary band",
    notConfiguredTitle: "No salary band configured",
    notConfiguredDescription:
      "Salary band reference is unavailable for this grade or legal entity.",
  },
  participantDetail: {
    backLabel: "Back to cycle",
    recommendationsTitle: "Participant recommendations",
    recommendationsDescription:
      "Merit, promotion, market, equity, and retention proposals for this employee (HRM-CPM-008..012).",
  },
  recommendationForm: {
    title: "Propose compensation adjustment",
    description:
      "Enter an increase by amount or percentage. Justification is required for exceptions.",
    adjustmentTypeLabel: "Adjustment type",
    increaseModeAmount: "Fixed amount",
    increaseModePercent: "Percentage",
    increaseAmountLabel: "Increase amount",
    increasePercentLabel: "Increase percent",
    managerCommentsLabel: "Manager comments",
    justificationLabel: "Justification",
    submitLabel: "Save recommendation",
    promotionGradeLabel: "Proposed grade",
    promotionLevelLabel: "Proposed level",
    marketPercentileLabel: "Market percentile reference",
    equityGapLabel: "Equity gap reference",
    retentionRiskLabel: "Retention risk level",
  },
  approvalStatusLabel: "Approval status",
  lockedBadge: "Locked",
  submitRecommendation: "Submit for review",
  reviewApprove: "Approve",
  reviewAdjust: "Adjust and approve",
  reviewReturn: "Return to manager",
  reviewReject: "Reject",
  notesLabel: "Review notes",
  proposedSalaryLabel: "Adjusted proposed salary",
  finalizeApproval: "Finalize approval",
  effectiveDateLabel: "Effective date",
} as const;
