export const hrBonusUiCopy = {
  page: {
    title: "Bonus & Incentive",
    description:
      "Plans, eligibility, cycles, targets, guaranteed rules, multipliers, proration, adjustments, discretionary recommendations, and recoveries.",
  },
  accessDenied: {
    title: "Bonus access restricted",
    description: "You need hr.bonus.read to view bonus and incentive configuration.",
  },
  plans: {
    surfaceHeaderTitle: "Bonus & incentive plans",
    searchLabel: "Search plans",
    searchPlaceholder: "Code, name, plan type…",
    emptyTitle: "No bonus plans",
    emptyDescription:
      "Create annual bonus, commission, incentive, and discretionary plans with eligibility and payout configuration.",
    colCode: "Code",
    colName: "Plan",
    colPlanType: "Type",
    colStatus: "Status",
    colCurrency: "Currency",
    colEffectiveFrom: "Effective from",
  },
  eligibilityRules: {
    surfaceHeaderTitle: "Eligibility rules",
    searchLabel: "Search eligibility rules",
    searchPlaceholder: "Plan, entity, role…",
    emptyTitle: "No eligibility rules",
    emptyDescription:
      "Define eligibility by legal entity, department, grade, role, tenure, performance rating, and employee status.",
    colPlan: "Plan",
    colScope: "Scope",
    colActive: "Status",
    colEffectiveFrom: "Effective from",
  },
  participants: {
    surfaceHeaderTitle: "Plan participants",
    searchLabel: "Search participants",
    searchPlaceholder: "Employee, plan…",
    emptyTitle: "No plan participants",
    emptyDescription:
      "Assign eligible employees to bonus or incentive plans. Ineligible employees are flagged on assignment.",
    colEmployee: "Employee",
    colPlan: "Plan",
    colStatus: "Assignment",
    colEligible: "Eligibility",
    colReason: "Ineligibility reason",
    colAssignedAt: "Assigned",
  },
  cycles: {
    surfaceHeaderTitle: "Bonus & incentive cycles",
    searchLabel: "Search cycles",
    searchPlaceholder: "Plan, cycle code…",
    emptyTitle: "No bonus cycles",
    emptyDescription:
      "Configure period start, end, cutoff, approval, and payout dates for each plan cycle.",
    colPlan: "Plan",
    colCode: "Code",
    colName: "Cycle",
    colStatus: "Status",
    colPeriod: "Period",
    colPayoutAt: "Payout date",
  },
  targets: {
    surfaceHeaderTitle: "Targets",
    searchLabel: "Search targets",
    searchPlaceholder: "Plan, cycle, scope…",
    emptyTitle: "No targets recorded",
    emptyDescription:
      "Record individual, team, department, company, sales, revenue, profit, project, and KPI targets.",
    colPlan: "Plan",
    colCycle: "Cycle",
    colKind: "Kind",
    colScope: "Scope",
    colTarget: "Target value",
    colCurrency: "Currency",
  },
  guaranteedRules: {
    surfaceHeaderTitle: "Guaranteed bonus rules",
    searchLabel: "Search guaranteed rules",
    searchPlaceholder: "Plan, label…",
    emptyTitle: "No guaranteed bonus rules",
    emptyDescription:
      "Define minimum guaranteed payouts per plan where contractual or policy guarantees apply.",
    colPlan: "Plan",
    colLabel: "Rule",
    colMinimum: "Minimum",
    colCurrency: "Currency",
    colActive: "Status",
  },
  multipliers: {
    surfaceHeaderTitle: "Performance multipliers",
    searchLabel: "Search multipliers",
    searchPlaceholder: "Plan, scope…",
    emptyTitle: "No performance multipliers",
    emptyDescription:
      "Configure company, department, team, and individual performance multipliers.",
    colPlan: "Plan",
    colScope: "Scope",
    colMultiplier: "Multiplier",
    colEffectiveFrom: "Effective from",
    colActive: "Status",
  },
  prorations: {
    surfaceHeaderTitle: "Bonus proration",
    searchLabel: "Search prorations",
    searchPlaceholder: "Employee, plan, cycle…",
    emptyTitle: "No proration records",
    emptyDescription:
      "Apply proration for new joiners, resignations, unpaid leave, or partial eligibility.",
    colEmployee: "Employee",
    colPlan: "Plan",
    colCycle: "Cycle",
    colReason: "Reason",
    colFactor: "Factor",
    colPeriod: "Period",
  },
  manualAdjustments: {
    surfaceHeaderTitle: "Manual adjustments",
    searchLabel: "Search adjustments",
    searchPlaceholder: "Employee, justification…",
    emptyTitle: "No manual adjustments",
    emptyDescription:
      "Manual payout adjustments require justification and an approval reference.",
    colEmployee: "Employee",
    colPlan: "Plan",
    colAmount: "Amount",
    colJustification: "Justification",
    colApprovalRef: "Approval ref",
    colStatus: "Status",
  },
  discretionary: {
    surfaceHeaderTitle: "Discretionary recommendations",
    searchLabel: "Search recommendations",
    searchPlaceholder: "Employee, rationale…",
    emptyTitle: "No discretionary recommendations",
    emptyDescription: "Track discretionary bonus recommendations before approval.",
    colEmployee: "Employee",
    colPlan: "Plan",
    colAmount: "Recommended",
    colStatus: "Status",
    colRecommender: "Recommender",
  },
  recoveries: {
    surfaceHeaderTitle: "Recoveries & clawback",
    searchLabel: "Search recoveries",
    searchPlaceholder: "Employee, reference…",
    emptyTitle: "No recovery records",
    emptyDescription:
      "Record commission reversals, payout corrections, overpayment recovery, and clawback references.",
    colEmployee: "Employee",
    colKind: "Kind",
    colAmount: "Amount",
    colReference: "Reference",
    colClawback: "Clawback ref",
    colRecordedAt: "Recorded",
  },
} as const;
