export const hrGeoUiCopy = {
  page: {
    title: "Geolocation & Remote Check-In",
    description:
      "Configure geofences, validate remote check-ins, route exceptions, and publish verified attendance to Leave & Attendance.",
  },
  accessDenied: {
    title: "Geolocation access required",
    description:
      "You need geolocation read permission to view remote check-in configuration, history, and exceptions.",
  },
  stats: {
    verifiedToday: "Verified today",
    pendingExceptions: "Pending exceptions",
    outsideGeofence: "Outside geofence flags",
    weakGps: "Weak GPS flags",
  },
  geofences: {
    sectionTitle: "Approved geofences",
    surfaceHeaderTitle: "Remote work geofences",
    searchLabel: "Search geofences",
    searchPlaceholder: "Label, project, or client site",
    emptyTitle: "No geofences configured",
    emptyDescription: "Define office, branch, project, client, field, or home office boundaries.",
    colLabel: "Location",
    colKind: "Kind",
    colRadius: "Radius (m)",
    colEmployee: "Scope",
  },
  policies: {
    sectionTitle: "Check-in policies",
    surfaceHeaderTitle: "Remote check-in policies",
    searchLabel: "Search policies",
    searchPlaceholder: "Policy group or label",
    emptyTitle: "No policies",
    emptyDescription: "Policy groups control eligibility, GPS thresholds, and device rules.",
    colLabel: "Policy",
    colGroup: "Group",
    colDevice: "Device check",
    colSelfie: "Selfie",
  },
  devices: {
    sectionTitle: "Registered devices",
    surfaceHeaderTitle: "Employee devices",
    searchLabel: "Search devices",
    searchPlaceholder: "Employee or fingerprint",
    emptyTitle: "No registered devices",
    emptyDescription: "Registered devices are verified during remote check-in when enabled.",
    colEmployee: "Employee",
    colDevice: "Device",
    colStatus: "Status",
    colRegistered: "Registered",
  },
  pending: {
    sectionTitle: "Pending exceptions",
    surfaceHeaderTitle: "Check-in exceptions",
    searchLabel: "Search exceptions",
    searchPlaceholder: "Employee or reason",
    emptyTitle: "No pending exceptions",
    emptyDescription: "Failed or outside-geofence check-ins awaiting review appear here.",
    colEmployee: "Employee",
    colReason: "Reason",
    colFlags: "Flags",
    colSubmitted: "Submitted",
    colActions: "Actions",
    trailingReasonLabel: "Decision reason",
    trailingApproveLabel: "Approve",
    trailingRejectLabel: "Reject",
    trailingReturnLabel: "Return",
  },
  history: {
    sectionTitle: "Check-in history",
    surfaceHeaderTitle: "Remote check-in history",
    searchLabel: "Search history",
    searchPlaceholder: "Employee name or number",
    emptyTitle: "No check-ins yet",
    emptyDescription: "Captured remote check-ins with validation outcomes are listed here.",
    colEmployee: "Employee",
    colAction: "Action",
    colStatus: "Status",
    colCaptured: "Captured",
    colLocation: "Location",
  },
  reports: {
    sectionTitle: "Reports",
    surfaceHeaderTitle: "Remote check-in summary",
    searchLabel: "Group by",
    searchPlaceholder: "department, employee, site, …",
    emptyTitle: "No report data",
    emptyDescription: "Adjust grouping to summarize verified, pending, and exception check-ins.",
    colGroup: "Group",
    colVerified: "Verified",
    colPending: "Pending",
    colExceptions: "Exceptions",
  },
  rawVsApproved: {
    sectionTitle: "Raw vs approved outcomes",
    surfaceHeaderTitle: "Capture ledger vs approved day",
    searchLabel: "Search rows",
    searchPlaceholder: "Employee name or number",
    emptyTitle: "No comparison rows",
    emptyDescription:
      "Remote captures without a materialized outcome, or approved days with raw punch volume.",
    colEmployee: "Employee",
    colWorkDate: "Work date",
    colRelationship: "Relationship",
    colRawCount: "Raw captures",
  },
  lamExposure: {
    sectionTitle: "LAM attendance handoff",
    surfaceHeaderTitle: "Verified remote check-ins exposed to LAM",
    searchLabel: "Search exposure rows",
    searchPlaceholder: "Employee name or number",
    emptyTitle: "No LAM exposure rows",
    emptyDescription: "Verified or corrected outcomes with Leave & Attendance linkage.",
    colEmployee: "Employee",
    colWorkDate: "Work date",
    colStatus: "Exposure",
    colLamRef: "LAM record",
  },
  overtimeRef: {
    sectionTitle: "Overtime reference",
    surfaceHeaderTitle: "Remote work-hour references for OTM",
    searchLabel: "Search OTM rows",
    searchPlaceholder: "Employee name or number",
    emptyTitle: "No overtime references",
    emptyDescription: "Outcomes with overtime reference payloads for Overtime Management.",
    colEmployee: "Employee",
    colWorkDate: "Work date",
    colStatus: "Outcome",
    colReference: "OTM reference",
  },
  payrollRef: {
    sectionTitle: "Payroll reference",
    surfaceHeaderTitle: "Approved remote outcomes for payroll",
    searchLabel: "Search payroll rows",
    searchPlaceholder: "Employee name or number",
    emptyTitle: "No payroll references",
    emptyDescription: "Outcomes linked to payroll day references through LAM.",
    colEmployee: "Employee",
    colWorkDate: "Work date",
    colStatus: "Readiness",
    colReference: "Payroll day ref",
  },
  auditTrail: {
    sectionTitle: "Audit trail",
    surfaceHeaderTitle: "Geolocation audit events",
    searchLabel: "Search audit events",
    searchPlaceholder: "Action or audit key",
    emptyTitle: "No audit events",
    emptyDescription: "Capture, validation, exception, and integration audit history.",
    colAction: "Action",
    colAuditKey: "Audit key",
    colOccurred: "Occurred",
  },
  capture: {
    sectionTitle: "Remote check-in",
    description:
      "Capture check-in or check-out with a one-time GPS read. Afenda does not track location between explicit events.",
    actionCheckIn: "Check in",
    actionCheckOut: "Check out",
    actionBreakStart: "Break start",
    actionBreakEnd: "Break end",
    capturing: "Resolving location…",
    success: "Check-in captured",
    error: "Could not capture check-in",
  },
} as const;
