export const hrSftUiCopy = {
  page: {
    title: "Shift Scheduling",
    description:
      "Manage shift rosters, compare attendance, payroll references, reports, and audit history.",
  },
  accessDenied: {
    title: "Access restricted",
    description:
      "You do not have permission to view shift scheduling for this organization.",
  },
  templates: {
    sectionTitle: "Shift types",
    surfaceHeaderTitle: "Shift types",
    searchLabel: "Search shift types",
    searchPlaceholder: "Code or name",
    emptyTitle: "No shift types yet",
    emptyDescription: "Create a shift type to start building rosters.",
    colCode: "Code",
    colName: "Name",
    colHours: "Working hours",
    colCategory: "Category",
    colPattern: "Pattern",
  },
  roster: {
    sectionTitle: "Shift roster",
    surfaceHeaderTitle: "Shift roster",
    searchLabel: "Search roster",
    searchPlaceholder: "Employee, shift, or notes",
    emptyTitle: "No shifts in this period",
    emptyDescription: "Adjust filters or assign shifts for the selected date range.",
    colEmployee: "Employee",
    colDate: "Date",
    colShift: "Shift",
    colStatus: "Status",
    colLocation: "Location",
  },
  recurrenceRules: {
    sectionTitle: "Recurrence rules",
    surfaceHeaderTitle: "Recurring shift rules",
    searchLabel: "Search recurrence rules",
    searchPlaceholder: "Code or name",
    emptyTitle: "No recurrence rules",
    emptyDescription: "Create weekly recurrence rules to generate shift assignments.",
    colCode: "Code",
    colName: "Name",
    colDays: "Days",
    colEffective: "Effective",
    colStatus: "Status",
  },
  coverage: {
    sectionTitle: "Coverage compare",
    surfaceHeaderTitle: "Coverage compare",
    searchLabel: "Search coverage",
    searchPlaceholder: "Shift, department, location…",
    emptyTitle: "No coverage requirements",
    emptyDescription:
      "Define minimum staffing requirements by shift, role, team, location, and date.",
    colDate: "Date",
    colShift: "Shift",
    colScope: "Scope",
    colRequired: "Required",
    colAssigned: "Assigned",
    colDelta: "Delta",
    colStatus: "Staffing",
  },
  publications: {
    sectionTitle: "Roster publications",
    surfaceHeaderTitle: "Published rosters",
    searchLabel: "Search publications",
    searchPlaceholder: "Notes or publisher",
    emptyTitle: "No publications",
    emptyDescription: "Published rosters appear here after a roster publish action.",
    colPeriod: "Period",
    colPublished: "Published",
    colPublisher: "Publisher",
  },
  notifications: {
    sectionTitle: "Schedule notifications",
    surfaceHeaderTitle: "Employee schedule alerts",
    searchLabel: "Search notifications",
    searchPlaceholder: "Title, body, or kind",
    emptyTitle: "No notifications",
    emptyDescription:
      "Employees are notified when schedules are published or changed.",
    colTitle: "Alert",
    colKind: "Kind",
    colWhen: "Sent",
  },
  attendanceReconcile: {
    sectionTitle: "Attendance reconcile",
    surfaceHeaderTitle: "Scheduled vs actual attendance",
    searchLabel: "Search reconcile rows",
    searchPlaceholder: "Employee, number, or shift code",
    emptyTitle: "No reconcile rows",
    emptyDescription:
      "Compare published shift assignments with LAM attendance records.",
    colEmployee: "Employee",
    colShift: "Scheduled shift",
    colAttendance: "Attendance",
    colStatus: "Alignment",
  },
  payrollRefs: {
    sectionTitle: "Payroll references",
    surfaceHeaderTitle: "Shift payroll exposure",
    searchLabel: "Search payroll refs",
    searchPlaceholder: "Employee, kind, or template",
    emptyTitle: "No payroll references",
    emptyDescription:
      "Planned overtime, shift premium, rest day, and holiday work references for Payroll Processing.",
    colEmployee: "Employee",
    colKind: "Kind",
    colShift: "Shift",
    colReady: "Payroll ready",
  },
  reports: {
    sectionTitle: "Schedule reports",
    surfaceHeaderTitle: "Saved report definitions",
    searchLabel: "Search report definitions",
    searchPlaceholder: "Code or name",
    emptyTitle: "No saved reports",
    emptyDescription:
      "Save filter presets for shift schedule reports by employee, department, team, manager, location, role, and period.",
    colCode: "Code",
    colName: "Name",
    colCreated: "Created",
  },
  audit: {
    sectionTitle: "Audit trail",
    surfaceHeaderTitle: "Shift scheduling audit",
    searchLabel: "Search audit trail",
    searchPlaceholder: "Action, summary, or actor",
    emptyTitle: "No audit events",
    emptyDescription:
      "Shift creation, assignment, publication, swap, approval, override, and payroll reference actions appear here.",
    colAction: "Action",
    colSummary: "Summary",
    colWhen: "When",
  },
  swapPending: {
    sectionTitle: "Swap approval inbox",
    surfaceHeaderTitle: "Swap approval inbox",
    searchLabel: "Search swaps",
    searchPlaceholder: "Employee, reason…",
    emptyTitle: "No pending swap requests",
    emptyDescription:
      "Employee shift swap requests awaiting manager review appear here.",
    colRequester: "Requester",
    colTarget: "Target",
    colStatus: "Status",
    colReason: "Reason",
    colSubmitted: "Submitted",
    trailingActions: "Actions",
  },
  mySwaps: {
    sectionTitle: "My swap requests",
    surfaceHeaderTitle: "My swap requests",
    searchLabel: "Search my swaps",
    searchPlaceholder: "Reason, status…",
    emptyTitle: "No swap requests",
    emptyDescription: "Submit a shift swap request when policy allows.",
    colTarget: "Target employee",
    colStatus: "Status",
    colReason: "Reason",
    colSubmitted: "Submitted",
    colDecision: "Decision",
  },
  scheduleChangePending: {
    sectionTitle: "Schedule change inbox",
    surfaceHeaderTitle: "Schedule change inbox",
    searchLabel: "Search changes",
    searchPlaceholder: "Employee, reason…",
    emptyTitle: "No pending schedule changes",
    emptyDescription:
      "Manager review queue for employee and manager-initiated schedule changes.",
    colEmployee: "Employee",
    colStatus: "Status",
    colReason: "Reason",
    colSubmitted: "Submitted",
    trailingActions: "Actions",
  },
  availability: {
    sectionTitle: "Employee availability",
    surfaceHeaderTitle: "Availability windows",
    searchLabel: "Search availability",
    searchPlaceholder: "Kind or reason",
    emptyTitle: "No availability records",
    emptyDescription:
      "Track unavailable, preferred, and blocked dates before assigning shifts.",
    colKind: "Kind",
    colStart: "Start",
    colEnd: "End",
    colReason: "Reason",
  },
  myScheduleChanges: {
    sectionTitle: "My schedule changes",
    surfaceHeaderTitle: "My schedule change requests",
    searchLabel: "Search my changes",
    searchPlaceholder: "Reason or status",
    emptyTitle: "No schedule change requests",
    emptyDescription: "Submit a schedule change request when policy allows.",
    colStatus: "Status",
    colReason: "Reason",
    colSubmitted: "Submitted",
    colDecision: "Decision",
  },
} as const;
