export const hrBenefitsUiCopy = {
  page: {
    title: "Benefits",
    description:
      "Manage benefit plans, eligibility, enrollment, coverage, contributions, and payroll deduction references.",
  },
  accessDenied: {
    title: "Benefits access restricted",
    description:
      "You need HR benefits read permission to view the benefits workbench.",
  },
  sensitiveAccess: {
    enrollmentsDescription:
      "Employee and employer contribution amounts are restricted. Request hr.benefits.sensitive.read to view payroll-related benefit amounts.",
    reportsDescription:
      "Cost and payroll deduction report exports mask contribution amounts without sensitive read permission.",
  },
  reports: {
    sectionTitle: "Benefits reports",
    sectionDescription:
      "Export enrollment, cost, and payroll deduction registers as CSV.",
    costLabel: "Cost report",
    enrollmentLabel: "Enrollment report",
    deductionLabel: "Payroll deduction report",
    downloadLabel: "Download CSV",
  },
  eligibilityRules: {
    surfaceHeaderTitle: "Eligibility rules",
    searchLabel: "Search rules",
    searchPlaceholder: "Plan, country, or entity",
    emptyTitle: "No eligibility rules",
    emptyDescription:
      "Configure who may enroll in each benefit plan by scope and tenure.",
    colPlanCode: "Plan code",
    colPlanName: "Plan",
    colScope: "Scope",
    colActive: "Active",
    colEffectiveFrom: "Effective from",
  },
  openEnrollment: {
    surfaceHeaderTitle: "Open enrollment windows",
    searchLabel: "Search windows",
    searchPlaceholder: "Code or name",
    emptyTitle: "No open enrollment windows",
    emptyDescription:
      "Define controlled enrollment periods and linked benefit plans.",
    colCode: "Code",
    colName: "Name",
    colStatus: "Status",
    colEnrollmentStart: "Enrollment start",
    colEnrollmentEnd: "Enrollment end",
    colPlanCount: "Plans",
  },
  plans: {
    surfaceHeaderTitle: "Benefit plans",
    searchLabel: "Search plans",
    searchPlaceholder: "Code, name, or category",
    emptyTitle: "No benefit plans",
    emptyDescription: "Configure benefit plans with categories and eligibility rules.",
    colCode: "Code",
    colName: "Name",
    colCategory: "Category",
    colProvider: "Provider",
    colStatus: "Status",
    colEffectiveFrom: "Effective from",
  },
  enrollments: {
    surfaceHeaderTitle: "Benefit enrollments",
    searchLabel: "Search enrollments",
    searchPlaceholder: "Employee or plan",
    emptyTitle: "No benefit enrollments",
    emptyDescription: "Enroll eligible employees into active benefit plans.",
    colEmployee: "Employee",
    colPlan: "Plan",
    colCoverageLevel: "Coverage level",
    colCoverageStatus: "Coverage status",
    colCoverageStart: "Coverage start",
    colEmployeeContribution: "Employee contribution",
    colEmployerContribution: "Employer contribution",
    createTitle: "Enroll employee",
    createDescription:
      "Eligible employees may enroll unless an authorized override reference is supplied.",
    createSubmitLabel: "Create enrollment",
    trailingApproveLabel: "Approve enrollment",
    trailingVerifyDependentsLabel: "Verify dependents",
    trailingAddDependentLabel: "Add dependent",
    dependentNameLabel: "Dependent name",
    dependentRelationshipLabel: "Relationship",
    dependentDobLabel: "Date of birth",
    eligibilityOverrideLabel: "Eligibility override reference",
  },
  providers: {
    surfaceHeaderTitle: "Benefit providers",
    searchLabel: "Search providers",
    searchPlaceholder: "Code or name",
    emptyTitle: "No benefit providers",
    emptyDescription: "Maintain insurance and benefit vendor references.",
    colCode: "Code",
    colName: "Name",
    colActive: "Active",
  },
  auditTrail: {
    surfaceHeaderTitle: "Benefits audit trail",
    searchLabel: "Search audit trail",
    searchPlaceholder: "Action or summary",
    emptyTitle: "No benefits audit events",
    emptyDescription: "Enrollment, waiver, and deduction actions appear here.",
    colAction: "Action",
    colSummary: "Summary",
    colOccurredAt: "Occurred at",
  },
} as const;
