export { hrComplianceExceptionsSurfaceKey } from "./hr.workforce.compliance-exceptions-list.surface";
export { hrComplianceLaborLawRequirementsSurfaceKey } from "./hr.workforce.compliance-labor-law-requirements-list.surface";
export { hrComplianceObligationsSurfaceKey } from "./hr.workforce.compliance-obligations-list.surface";

export const hrComplianceUiCopy = {
  page: {
    title: "Compliance",
    description:
      "Configure HR compliance obligations and track labor law requirements applicable to employees.",
  },
  accessDenied: {
    title: "Access restricted",
    description: "Compliance records are not available for this account.",
  },
  obligations: {
    sectionTitle: "Compliance obligations",
    sectionDescription:
      "Register obligations scoped by legal entity, country, location, employment type, and worker category.",
    surfaceHeaderTitle: "Obligation register",
    emptyTitle: "No compliance obligations configured",
    emptyDescription:
      "Configure obligations by legal entity, country, location, employment type, and worker category.",
    searchLabel: "Search obligations",
    searchPlaceholder: "Search by code, title, or area",
    colCode: "Code",
    colTitle: "Title",
    colKind: "Kind",
    colArea: "Area",
    colStatus: "Status",
    colScope: "Scope",
    colDue: "Due",
    colActions: "Actions",
    trailingArchiveLabel: "Archive",
    trailingArchiveDisabledReason: "Archived obligations cannot be changed.",
    registerTitle: "Configure obligation",
    registerDescription:
      "Save a new obligation or update an existing register entry by code.",
    formSubmitLabel: "Save obligation",
    formFieldCode: "Code",
    formFieldTitle: "Title",
    formFieldDescription: "Description",
    formFieldRequirementKind: "Requirement kind",
    formFieldComplianceArea: "Compliance area",
    formFieldCountry: "Country",
    formFieldLegalEntity: "Legal entity",
    formFieldDepartment: "Department",
    formFieldDepartmentAll: "All departments",
    formFieldWorkLocation: "Work location",
    formFieldEmploymentType: "Employment type",
    formFieldWorkerCategory: "Worker category",
    formFieldDueDate: "Due date",
    formFieldCountryPlaceholder: "MY",
  },
  exceptions: {
    sectionTitle: "Open exceptions",
    sectionDescription:
      "Track non-compliance cases, corrective actions, and waiver requests.",
    surfaceHeaderTitle: "Open exceptions",
    emptyTitle: "No open exceptions",
    emptyDescription:
      "Open compliance exceptions appear here when an obligation gap is recorded.",
    searchLabel: "Search exceptions",
    searchPlaceholder: "Search by title, employee, or area",
    colTitle: "Title",
    colEmployee: "Employee",
    colArea: "Area",
    colSeverity: "Severity",
    colStatus: "Status",
    colDue: "Corrective due",
    colActions: "Actions",
    trailingClosedDisabledReason:
      "Closed exceptions cannot receive new corrective actions.",
    trailingAssignLabel: "Assign corrective action",
    trailingProgressLabel: "Update progress",
    trailingResolveLabel: "Resolve",
    trailingWaiveLabel: "Waive",
    trailingCorrectiveDescriptionPlaceholder: "Corrective action",
    trailingCorrectiveDuePlaceholder: "Corrective due date",
    trailingProgressPlaceholder: "Progress note",
    trailingResolutionPlaceholder: "Resolution note",
    trailingWaiverReasonPlaceholder: "Waiver reason",
    trailingApprovalReferencePlaceholder: "Approval reference",
    trailingReviewNotesPlaceholder: "Review notes",
    createTitle: "Record exception",
    createDescription: "Open a compliance exception for follow-up.",
    formSubmitLabel: "Create exception",
    formFieldTitle: "Title",
    formFieldItemType: "Item type",
    formFieldArea: "Area",
    formFieldSeverity: "Severity",
  },
  laborLaw: {
    sectionTitle: "Labor law requirements",
    sectionDescription:
      "Track labor law compliance requirements applicable to each employee based on obligation scope.",
    surfaceHeaderTitle: "Employee labor law register",
    emptyTitle: "No labor law requirements tracked",
    emptyDescription:
      "Configure labor law obligations and sync applicable requirements for active employees.",
    searchLabel: "Search labor law requirements",
    searchPlaceholder: "Search by employee, requirement code, or area",
    colEmployee: "Employee",
    colRequirement: "Requirement",
    colArea: "Area",
    colStatus: "Status",
    colDue: "Due",
    colCompleted: "Completed",
    colActions: "Actions",
    syncTitle: "Sync applicable requirements",
    syncDescription:
      "Materialize labor law obligation rows for active employees whose scope matches configured obligations.",
    syncActionLabel: "Sync requirements",
    trailingMarkCompliantLabel: "Update status",
    trailingUpdateStatusLabel: "Requirement status",
    trailingReviewNotesPlaceholder: "Review notes",
  },
} as const;
