export const systemAdminApprovalsUiCopy = {
  page: {
    title: "Approvals",
    description:
      "Approval law is configured here. Orbit and workflow runtime create tasks; System Admin does not execute workflow work directly.",
  },
  list: {
    title: "Approval rules",
    searchPlaceholder: "Search approval rules by name, module, or action",
    emptyTitle: "No approval rules are configured for this organization.",
    emptyDescription:
      "Create or update a rule in the editor below when you have system-admin.approvals.manage.",
    emptyDescriptionReadOnly:
      "Ask an administrator with system-admin.approvals.manage to configure approval rules for this organization.",
    actionsHeader: "Actions",
    reviewActionLabel: "Review",
    enableActionLabel: "Enable",
    disableActionLabel: "Disable",
    columns: {
      name: "Rule",
      moduleKey: "Module",
      action: "Action",
      targetType: "Target",
      approvalMode: "Mode",
      approverRoles: "Approvers",
      minApprovals: "Min approvals",
      escalation: "Escalation",
      status: "Status",
      readinessVerdict: "Readiness",
    },
  },
  editor: {
    title: "Create or update approval rule",
    updateTitle: "Update selected approval rule",
    description:
      "Approver roles are validated against organization roles. Disabled rules do not affect execution kernel verdicts.",
    footnote:
      "Approval law is configured here. Workflow runtime creates tasks; System Admin does not execute approvals directly.",
    submitCreate: "Save approval rule",
    submitUpdate: "Update approval rule",
    fields: {
      approvalKey: "Approval key",
      name: "Display name",
      moduleKey: "Module",
      action: "Action",
      targetType: "Target type",
      approvalMode: "Approval mode",
      approverRoleKeys: "Approver roles",
      delegateToRoleKeys: "Delegation roles (optional)",
      delegationValidDays: "Delegation valid days",
      minApprovals: "Minimum approvals",
      escalationAfterHours: "Escalation (hours)",
      escalationBehavior: "Escalation behavior",
      escalationRoleKeys: "Escalation roles",
      status: "Status",
      enabled: "Enabled",
    },
    placeholders: {
      approvalKey: "purchasing.po.high-value",
      name: "Purchase order above threshold",
      moduleKey: "purchasing",
      action: "purchasing.purchase-order.create",
      approverRoleKeys: "finance-manager,owner",
      delegateToRoleKeys: "operations-manager",
      delegationValidDays: "30",
      escalationAfterHours: "24",
      escalationRoleKeys: "owner",
    },
    modes: {
      sequential: "Sequential",
      parallel: "Parallel",
    },
    escalationBehaviors: {
      notify: "Notify",
      reassign: "Reassign",
      expire: "Expire",
    },
    statuses: {
      active: "Active",
      disabled: "Disabled",
      deprecated: "Deprecated",
    },
    enabledOptions: {
      true: "Enabled",
      false: "Disabled",
    },
  },
  accessDenied: {
    title: "Approval rules unavailable",
    description:
      "You need system-admin.approvals.read, system-admin.approvals.review, or system-admin.settings.read to review approval configuration.",
  },
  detail: {
    backLabel: "Back to catalog",
    auditHistoryLabel: "View approval audit history",
    noCapability: "No registered execution capability",
    notConfigured: "Not configured",
    enabledYes: "Yes",
    enabledNo: "No",
    fields: {
      approvalKey: "Approval key",
      module: "Module",
      approvalMode: "Approval mode",
      status: "Status",
      minApprovals: "Minimum approvals",
      readiness: "Readiness",
      escalation: "Escalation",
      escalationBehavior: "Escalation behavior",
      escalationRoles: "Escalation roles",
      delegationValidDays: "Delegation valid days",
      enabled: "Enabled",
      action: "Action",
      approverRoles: "Approver roles",
      delegationRoles: "Delegation roles",
      capability: "Capability",
      requiredPermission: "Required permission",
      relatedPolicies: "Related policies",
    },
    recentActivityTitle: "Recent approval activity",
    noRecentActivityTitle: "No recent activity",
    noRecentActivityDescription:
      "Configuration changes and runtime audit events for this approval rule will appear here.",
    activityColumns: {
      when: "When",
      actor: "Actor",
      action: "Action",
      summary: "Summary",
    },
    reactivate: {
      actionLabel: "Reactivate after review",
      description:
        "Deprecated rules stay out of runtime until a reviewer with system-admin.approvals.review reactivates them.",
    },
  },
} as const;
