import type { SystemAdminApprovalRuleListRow } from "../contracts/system-admin.approval-rule.contract";

export const systemAdminApprovalsGalleryRows: readonly SystemAdminApprovalRuleListRow[] =
  [
    {
      id: "approval-gallery-1",
      key: "purchasing.po.approval",
      name: "High value purchase order",
      moduleKey: "purchasing",
      action: "purchasing.purchase-order.create",
      targetType: "erp-record",
      approvalMode: "sequential",
      approverRoles: "finance-manager, owner",
      minApprovals: 2,
      escalation: "24h · notify",
      status: "active",
      enabled: true,
      readinessVerdict: "ready",
    },
    {
      id: "approval-gallery-2",
      key: "finance.payment.release",
      name: "Payment release",
      moduleKey: "finance",
      action: "finance.documents.write",
      targetType: "erp-record",
      approvalMode: "parallel",
      approverRoles: "finance-manager",
      minApprovals: 1,
      escalation: "48h · reassign → owner",
      status: "active",
      enabled: true,
      readinessVerdict: "warning",
    },
    {
      id: "approval-gallery-3",
      key: "hr.salary.change",
      name: "Salary change",
      moduleKey: "hr",
      action: "hr.documents.write",
      targetType: "erp-record",
      approvalMode: "parallel",
      approverRoles: "admin",
      minApprovals: 1,
      escalation: "Not configured",
      status: "disabled",
      enabled: false,
      readinessVerdict: "warning",
    },
  ] as const;

export const systemAdminApprovalDetailGalleryFixture = {
  approvalKey: "purchasing.po.approval",
  name: "High value purchase order",
  moduleKey: "purchasing",
  action: "purchasing.purchase-order.create",
  targetType: "erp-record",
  approvalMode: "sequential" as const,
  approverRoleKeys: ["finance-manager", "owner"],
  delegateToRoleKeys: ["operations-manager"],
  delegationValidDays: 30,
  minApprovals: 2,
  escalationAfterHours: 24,
  escalationBehavior: "notify" as const,
  escalationRoleKeys: [] as readonly string[],
  status: "active" as const,
  enabled: true,
  readinessVerdict: "ready" as const,
  capabilityKey: null,
  capabilityLabel: null,
  requiredPermission: null,
  relatedPolicyKeys: ["purchasing.po.require-approval"],
  recentActivity: [
    {
      id: "audit-gallery-1",
      occurredAt: "1 Jun 2026, 09:00",
      actorId: "user-gallery-admin",
      action: "system-admin.approval_rule.update",
      summary: "Updated approval rule purchasing.po.approval",
    },
  ],
  auditHref: "/system-admin/audit?auditQ=purchasing.po.approval",
};
